// Code generated by goyacc - DO NOT EDIT.

package main

import __yyfmt__ "fmt"

import (
	cmd "cli/controllers"
	"strconv"
	"strings"
)

var root node

func resMap(x *string) map[string]interface{} {
	resarr := strings.Split(*x, "=")
	res := make(map[string]interface{})
	attrs := make(map[string]string)

	for i := 0; i+1 < len(resarr); {
		if i+1 < len(resarr) {
			switch resarr[i] {
			case "id", "name", "category", "parentID",
				"description", "domain", "parentid", "parentId":
				res[resarr[i]] = resarr[i+1]

			default:
				attrs[resarr[i]] = resarr[i+1]
			}
			i += 2
		}
	}
	res["attributes"] = attrs
	return res
}

func replaceOCLICurrPath(x string) string {
	return strings.Replace(x, "_", cmd.State.CurrPath, 1)
}

type yySymType struct {
	yys     int
	n       int
	s       string
	sarr    []string
	ast     *ast
	node    node
	nodeArr []node
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault      = 57427
	yyEofCode      = 57344
	TOK_AND        = 57415
	TOK_ATTR       = 57356
	TOK_ATTRSPEC   = 57390
	TOK_BASHTYPE   = 57365
	TOK_BLDG       = 57350
	TOK_BOOL       = 57359
	TOK_CD         = 57371
	TOK_CLR        = 57373
	TOK_CMDFLAG    = 57367
	TOK_CMDS       = 57401
	TOK_COL        = 57395
	TOK_COMMA      = 57399
	TOK_CREATE     = 57360
	TOK_DELETE     = 57363
	TOK_DEREF      = 57404
	TOK_DEVICE     = 57353
	TOK_DIV        = 57420
	TOK_DOC        = 57370
	TOK_DONE       = 57426
	TOK_DOT        = 57400
	TOK_ELSE       = 57409
	TOK_EQUAL      = 57366
	TOK_EXIT       = 57369
	TOK_FI         = 57425
	TOK_FOR        = 57407
	TOK_GET        = 57361
	TOK_GREATER    = 57422
	TOK_GREP       = 57374
	TOK_IF         = 57406
	TOK_IN         = 57416
	TOK_LBLOCK     = 57410
	TOK_LBRAC      = 57397
	TOK_LESS       = 57423
	TOK_LPAREN     = 57412
	TOK_LS         = 57375
	TOK_LSBLDG     = 57380
	TOK_LSDEV      = 57383
	TOK_LSOG       = 57377
	TOK_LSRACK     = 57382
	TOK_LSROOM     = 57381
	TOK_LSSITE     = 57379
	TOK_LSSUBDEV   = 57384
	TOK_LSSUBDEV1  = 57385
	TOK_LSTEN      = 57378
	TOK_MULT       = 57421
	TOK_NOT        = 57419
	TOK_NUM        = 57346
	TOK_OCBLDG     = 57386
	TOK_OCDEL      = 57358
	TOK_OCDEV      = 57387
	TOK_OCRACK     = 57388
	TOK_OCROOM     = 57389
	TOK_OCSDEV     = 57393
	TOK_OCSDEV1    = 57394
	TOK_OCSITE     = 57391
	TOK_OCTENANT   = 57392
	TOK_OR         = 57414
	TOK_PLUS       = 57357
	TOK_PRNT       = 57417
	TOK_PWD        = 57372
	TOK_QUOT       = 57418
	TOK_RACK       = 57352
	TOK_RBLOCK     = 57411
	TOK_RBRAC      = 57398
	TOK_ROOM       = 57351
	TOK_RPAREN     = 57413
	TOK_SEARCH     = 57364
	TOK_SELECT     = 57396
	TOK_SEMICOL    = 57405
	TOK_SITE       = 57349
	TOK_SLASH      = 57368
	TOK_SUBDEVICE  = 57354
	TOK_SUBDEVICE1 = 57355
	TOK_TEMPLATE   = 57402
	TOK_TENANT     = 57348
	TOK_THEN       = 57424
	TOK_TREE       = 57376
	TOK_UPDATE     = 57362
	TOK_VAR        = 57403
	TOK_WHILE      = 57408
	TOK_WORD       = 57347
	yyErrCode      = 57345

	yyMaxDepth = 200
	yyTabOfs   = -149
)

var (
	yyPrec = map[int]int{
		TOK_MULT:  0,
		TOK_OCDEL: 0,
		TOK_DIV:   0,
		TOK_PLUS:  0,
		TOK_EQUAL: 1,
	}

	yyXLAT = map[int]int{
		57426: 0,   // TOK_DONE (160x)
		57398: 1,   // TOK_RBRAC (158x)
		57425: 2,   // TOK_FI (156x)
		57344: 3,   // $end (155x)
		57405: 4,   // TOK_SEMICOL (155x)
		57409: 5,   // TOK_ELSE (154x)
		57413: 6,   // TOK_RPAREN (146x)
		57358: 7,   // TOK_OCDEL (126x)
		57347: 8,   // TOK_WORD (118x)
		57404: 9,   // TOK_DEREF (73x)
		57400: 10,  // TOK_DOT (68x)
		57346: 11,  // TOK_NUM (66x)
		57357: 12,  // TOK_PLUS (64x)
		57368: 13,  // TOK_SLASH (52x)
		57359: 14,  // TOK_BOOL (51x)
		57419: 15,  // TOK_NOT (48x)
		57390: 16,  // TOK_ATTRSPEC (47x)
		57366: 17,  // TOK_EQUAL (47x)
		57453: 18,  // P1 (44x)
		57452: 19,  // P (41x)
		57414: 20,  // TOK_OR (35x)
		57356: 21,  // TOK_ATTR (31x)
		57415: 22,  // TOK_AND (29x)
		57451: 23,  // ORIENTN (28x)
		57411: 24,  // TOK_RBLOCK (27x)
		57457: 25,  // WORDORNUM (27x)
		57412: 26,  // TOK_LPAREN (25x)
		57458: 27,  // factor (21x)
		57465: 28,  // unary (21x)
		57422: 29,  // TOK_GREATER (18x)
		57423: 30,  // TOK_LESS (18x)
		57420: 31,  // TOK_DIV (17x)
		57421: 32,  // TOK_MULT (17x)
		57464: 33,  // term (16x)
		57395: 34,  // TOK_COL (15x)
		57459: 35,  // nex (14x)
		57371: 36,  // TOK_CD (11x)
		57360: 37,  // TOK_CREATE (11x)
		57363: 38,  // TOK_DELETE (11x)
		57361: 39,  // TOK_GET (11x)
		57375: 40,  // TOK_LS (11x)
		57377: 41,  // TOK_LSOG (11x)
		57376: 42,  // TOK_TREE (11x)
		57362: 43,  // TOK_UPDATE (11x)
		57428: 44,  // BASH (10x)
		57434: 45,  // FUNC (10x)
		57437: 46,  // K (10x)
		57438: 47,  // NT_CREATE (10x)
		57439: 48,  // NT_DEL (10x)
		57440: 49,  // NT_GET (10x)
		57441: 50,  // NT_UPDATE (10x)
		57442: 51,  // OCCHOOSE (10x)
		57444: 52,  // OCDEL (10x)
		57445: 53,  // OCDOT (10x)
		57446: 54,  // OCGET (10x)
		57447: 55,  // OCLISYNTX (10x)
		57448: 56,  // OCSEL (10x)
		57449: 57,  // OCUPDATE (10x)
		57454: 58,  // Q (10x)
		57455: 59,  // REL (10x)
		57463: 60,  // stmnt (10x)
		57373: 61,  // TOK_CLR (10x)
		57370: 62,  // TOK_DOC (10x)
		57369: 63,  // TOK_EXIT (10x)
		57374: 64,  // TOK_GREP (10x)
		57380: 65,  // TOK_LSBLDG (10x)
		57383: 66,  // TOK_LSDEV (10x)
		57382: 67,  // TOK_LSRACK (10x)
		57381: 68,  // TOK_LSROOM (10x)
		57379: 69,  // TOK_LSSITE (10x)
		57384: 70,  // TOK_LSSUBDEV (10x)
		57385: 71,  // TOK_LSSUBDEV1 (10x)
		57378: 72,  // TOK_LSTEN (10x)
		57417: 73,  // TOK_PRNT (10x)
		57372: 74,  // TOK_PWD (10x)
		57396: 75,  // TOK_SELECT (10x)
		57429: 76,  // CTRL (9x)
		57450: 77,  // OPEN_STMT (9x)
		57461: 78,  // st2 (9x)
		57407: 79,  // TOK_FOR (9x)
		57406: 80,  // TOK_IF (9x)
		57418: 81,  // TOK_QUOT (9x)
		57408: 82,  // TOK_WHILE (9x)
		57431: 83,  // EQAL (8x)
		57436: 84,  // JOIN (7x)
		57432: 85,  // EXPR (6x)
		57433: 86,  // F (5x)
		57350: 87,  // TOK_BLDG (3x)
		57353: 88,  // TOK_DEVICE (3x)
		57397: 89,  // TOK_LBRAC (3x)
		57352: 90,  // TOK_RACK (3x)
		57351: 91,  // TOK_ROOM (3x)
		57349: 92,  // TOK_SITE (3x)
		57348: 93,  // TOK_TENANT (3x)
		57430: 94,  // E (2x)
		57435: 95,  // GETOBJS (2x)
		57456: 96,  // STRARG (2x)
		57354: 97,  // TOK_SUBDEVICE (2x)
		57355: 98,  // TOK_SUBDEVICE1 (2x)
		57443: 99,  // OCCR (1x)
		57460: 100, // opn (1x)
		57462: 101, // start (1x)
		57401: 102, // TOK_CMDS (1x)
		57399: 103, // TOK_COMMA (1x)
		57416: 104, // TOK_IN (1x)
		57410: 105, // TOK_LBLOCK (1x)
		57386: 106, // TOK_OCBLDG (1x)
		57387: 107, // TOK_OCDEV (1x)
		57388: 108, // TOK_OCRACK (1x)
		57389: 109, // TOK_OCROOM (1x)
		57391: 110, // TOK_OCSITE (1x)
		57392: 111, // TOK_OCTENANT (1x)
		57402: 112, // TOK_TEMPLATE (1x)
		57424: 113, // TOK_THEN (1x)
		57403: 114, // TOK_VAR (1x)
		57427: 115, // $default (0x)
		57345: 116, // error (0x)
		57365: 117, // TOK_BASHTYPE (0x)
		57367: 118, // TOK_CMDFLAG (0x)
		57393: 119, // TOK_OCSDEV (0x)
		57394: 120, // TOK_OCSDEV1 (0x)
		57364: 121, // TOK_SEARCH (0x)
	}

	yySymNames = []string{
		"TOK_DONE",
		"TOK_RBRAC",
		"TOK_FI",
		"$end",
		"TOK_SEMICOL",
		"TOK_ELSE",
		"TOK_RPAREN",
		"TOK_OCDEL",
		"TOK_WORD",
		"TOK_DEREF",
		"TOK_DOT",
		"TOK_NUM",
		"TOK_PLUS",
		"TOK_SLASH",
		"TOK_BOOL",
		"TOK_NOT",
		"TOK_ATTRSPEC",
		"TOK_EQUAL",
		"P1",
		"P",
		"TOK_OR",
		"TOK_ATTR",
		"TOK_AND",
		"ORIENTN",
		"TOK_RBLOCK",
		"WORDORNUM",
		"TOK_LPAREN",
		"factor",
		"unary",
		"TOK_GREATER",
		"TOK_LESS",
		"TOK_DIV",
		"TOK_MULT",
		"term",
		"TOK_COL",
		"nex",
		"TOK_CD",
		"TOK_CREATE",
		"TOK_DELETE",
		"TOK_GET",
		"TOK_LS",
		"TOK_LSOG",
		"TOK_TREE",
		"TOK_UPDATE",
		"BASH",
		"FUNC",
		"K",
		"NT_CREATE",
		"NT_DEL",
		"NT_GET",
		"NT_UPDATE",
		"OCCHOOSE",
		"OCDEL",
		"OCDOT",
		"OCGET",
		"OCLISYNTX",
		"OCSEL",
		"OCUPDATE",
		"Q",
		"REL",
		"stmnt",
		"TOK_CLR",
		"TOK_DOC",
		"TOK_EXIT",
		"TOK_GREP",
		"TOK_LSBLDG",
		"TOK_LSDEV",
		"TOK_LSRACK",
		"TOK_LSROOM",
		"TOK_LSSITE",
		"TOK_LSSUBDEV",
		"TOK_LSSUBDEV1",
		"TOK_LSTEN",
		"TOK_PRNT",
		"TOK_PWD",
		"TOK_SELECT",
		"CTRL",
		"OPEN_STMT",
		"st2",
		"TOK_FOR",
		"TOK_IF",
		"TOK_QUOT",
		"TOK_WHILE",
		"EQAL",
		"JOIN",
		"EXPR",
		"F",
		"TOK_BLDG",
		"TOK_DEVICE",
		"TOK_LBRAC",
		"TOK_RACK",
		"TOK_ROOM",
		"TOK_SITE",
		"TOK_TENANT",
		"E",
		"GETOBJS",
		"STRARG",
		"TOK_SUBDEVICE",
		"TOK_SUBDEVICE1",
		"OCCR",
		"opn",
		"start",
		"TOK_CMDS",
		"TOK_COMMA",
		"TOK_IN",
		"TOK_LBLOCK",
		"TOK_OCBLDG",
		"TOK_OCDEV",
		"TOK_OCRACK",
		"TOK_OCROOM",
		"TOK_OCSITE",
		"TOK_OCTENANT",
		"TOK_TEMPLATE",
		"TOK_THEN",
		"TOK_VAR",
		"$default",
		"error",
		"TOK_BASHTYPE",
		"TOK_CMDFLAG",
		"TOK_OCSDEV",
		"TOK_OCSDEV1",
		"TOK_SEARCH",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:   {0, 1},
		1:   {101, 1},
		2:   {78, 2},
		3:   {78, 3},
		4:   {78, 1},
		5:   {100, 1},
		6:   {100, 0},
		7:   {60, 1},
		8:   {60, 1},
		9:   {60, 1},
		10:  {60, 1},
		11:  {60, 0},
		12:  {76, 1},
		13:  {77, 7},
		14:  {77, 9},
		15:  {77, 6},
		16:  {77, 15},
		17:  {77, 7},
		18:  {77, 12},
		19:  {85, 3},
		20:  {85, 1},
		21:  {84, 3},
		22:  {84, 1},
		23:  {83, 4},
		24:  {83, 4},
		25:  {83, 1},
		26:  {59, 3},
		27:  {59, 4},
		28:  {59, 4},
		29:  {59, 3},
		30:  {59, 1},
		31:  {35, 3},
		32:  {35, 3},
		33:  {35, 1},
		34:  {33, 3},
		35:  {33, 3},
		36:  {33, 1},
		37:  {28, 2},
		38:  {28, 2},
		39:  {28, 1},
		40:  {27, 3},
		41:  {27, 1},
		42:  {27, 2},
		43:  {27, 1},
		44:  {27, 1},
		45:  {46, 1},
		46:  {46, 1},
		47:  {46, 1},
		48:  {46, 1},
		49:  {47, 3},
		50:  {47, 4},
		51:  {49, 2},
		52:  {49, 3},
		53:  {50, 3},
		54:  {48, 2},
		55:  {94, 1},
		56:  {94, 1},
		57:  {94, 1},
		58:  {94, 1},
		59:  {94, 1},
		60:  {94, 1},
		61:  {94, 1},
		62:  {94, 1},
		63:  {23, 1},
		64:  {23, 1},
		65:  {23, 0},
		66:  {25, 1},
		67:  {25, 1},
		68:  {25, 4},
		69:  {25, 1},
		70:  {86, 4},
		71:  {86, 3},
		72:  {19, 1},
		73:  {19, 2},
		74:  {18, 3},
		75:  {18, 1},
		76:  {18, 4},
		77:  {18, 1},
		78:  {18, 2},
		79:  {18, 1},
		80:  {18, 2},
		81:  {18, 0},
		82:  {58, 2},
		83:  {58, 2},
		84:  {58, 2},
		85:  {58, 2},
		86:  {58, 2},
		87:  {58, 2},
		88:  {58, 2},
		89:  {58, 2},
		90:  {58, 2},
		91:  {58, 2},
		92:  {58, 2},
		93:  {58, 2},
		94:  {58, 3},
		95:  {58, 1},
		96:  {44, 1},
		97:  {44, 1},
		98:  {44, 4},
		99:  {44, 1},
		100: {44, 1},
		101: {44, 1},
		102: {44, 1},
		103: {44, 2},
		104: {44, 2},
		105: {44, 2},
		106: {44, 2},
		107: {44, 2},
		108: {44, 2},
		109: {44, 2},
		110: {44, 2},
		111: {44, 2},
		112: {55, 2},
		113: {55, 1},
		114: {55, 1},
		115: {55, 1},
		116: {55, 1},
		117: {55, 1},
		118: {55, 1},
		119: {99, 5},
		120: {99, 5},
		121: {99, 5},
		122: {99, 5},
		123: {99, 7},
		124: {99, 7},
		125: {99, 7},
		126: {99, 7},
		127: {99, 7},
		128: {99, 7},
		129: {99, 7},
		130: {99, 7},
		131: {52, 2},
		132: {57, 5},
		133: {54, 2},
		134: {95, 3},
		135: {95, 1},
		136: {51, 4},
		137: {53, 6},
		138: {53, 4},
		139: {53, 4},
		140: {53, 2},
		141: {53, 4},
		142: {53, 4},
		143: {56, 1},
		144: {56, 5},
		145: {96, 2},
		146: {96, 0},
		147: {45, 6},
		148: {45, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [333][]uint16{
		// 0
		{3: 138, 138, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 151, 161, 159, 82: 160, 101: 150},
		{3: 149},
		{3: 148},
		{143, 143, 143, 143, 480, 143, 100: 479},
		{145, 145, 145, 145, 5: 145},
		// 5
		{142, 142, 142, 142, 142, 142, 142},
		{141, 141, 141, 141, 141, 141, 141},
		{140, 140, 140, 140, 140, 140, 140},
		{139, 139, 139, 139, 139, 139, 139},
		{137, 137, 137, 137, 5: 137},
		// 10
		{105: 470},
		{26: 465},
		{8: 437, 26: 436},
		{104, 104, 104, 104, 104, 104, 104},
		{103, 103, 103, 103, 103, 103, 103},
		// 15
		{102, 102, 102, 102, 102, 102, 102},
		{101, 101, 101, 101, 101, 101, 101},
		{87: 425, 428, 90: 427, 426, 424, 423, 432, 97: 429, 430},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 421, 87: 425, 428, 90: 427, 426, 424, 423, 422, 97: 429, 430},
		{7: 211, 209, 212, 210, 13: 171, 18: 170, 415, 21: 68},
		// 20
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 414},
		{77, 77, 77, 77, 77, 77, 77, 10: 77, 77, 16: 77, 21: 77},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 68, 16: 68, 18: 413, 21: 68},
		{1, 1, 1, 1, 1, 1, 1, 10: 74, 13: 224, 26: 408},
		{10: 221, 102: 398, 112: 399, 114: 397},
		// 25
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 396},
		{8: 343},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 342},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 341},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 340},
		// 30
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 339},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 338},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 337},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 336},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 335},
		// 35
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 334},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 333},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 330, 13: 171, 18: 170, 331},
		{54, 54, 54, 54, 54, 54, 54},
		{53, 53, 53, 53, 53, 53, 53},
		// 40
		{52, 52, 52, 52, 52, 52, 52},
		{81: 325},
		{50, 50, 50, 50, 50, 50, 50},
		{49, 49, 49, 49, 49, 49, 49},
		{48, 48, 48, 48, 48, 48, 48},
		// 45
		{47, 47, 47, 47, 47, 47, 47, 8: 322, 36: 317, 318, 321, 319, 316, 324, 323, 320},
		{87: 245, 251, 90: 249, 247, 243, 241, 99: 239, 106: 244, 250, 248, 246, 242, 240},
		{36, 36, 36, 36, 36, 36, 36},
		{35, 35, 35, 35, 35, 35, 35},
		{34, 34, 34, 34, 34, 34, 34},
		// 50
		{33, 33, 33, 33, 33, 33, 33},
		{32, 32, 32, 32, 32, 32, 32},
		{31, 31, 31, 31, 31, 31, 31},
		{10: 226},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 213, 89: 214},
		// 55
		{6, 6, 6, 6, 6, 6, 6, 10: 205},
		{21: 206},
		{17: 207},
		{8: 208},
		{5, 5, 5, 5, 5, 5, 5},
		// 60
		{74, 74, 74, 74, 74, 74, 74, 10: 74, 74, 13: 224, 16: 74, 21: 74},
		{10: 221},
		{70, 70, 70, 70, 70, 70, 70, 10: 70, 70, 16: 70, 21: 70},
		{8: 220},
		{16, 16, 16, 16, 16, 16, 16},
		// 65
		{8: 215, 95: 216},
		{1: 14, 103: 218},
		{1: 217},
		{13, 13, 13, 13, 13, 13, 13},
		{8: 215, 95: 219},
		// 70
		{1: 15},
		{69, 69, 69, 69, 69, 69, 69, 10: 69, 69, 16: 69, 21: 69},
		{71, 71, 71, 71, 71, 71, 71, 10: 71, 71, 13: 222, 16: 71, 21: 71},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 68, 16: 68, 18: 223, 21: 68},
		{73, 73, 73, 73, 73, 73, 73, 10: 73, 73, 16: 73, 21: 73},
		// 75
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 68, 16: 68, 18: 225, 21: 68},
		{75, 75, 75, 75, 75, 75, 75, 10: 75, 75, 16: 75, 21: 75},
		{21: 227},
		{17: 228},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 235},
		// 80
		{8: 86},
		{8: 85},
		{83, 83, 83, 83, 83, 83, 83, 83, 83, 11: 83, 83, 14: 83, 16: 83, 21: 83, 81: 83},
		{82, 82, 82, 82, 82, 82, 82, 82, 82, 11: 82, 82, 14: 82, 16: 82, 21: 82, 81: 82},
		{8: 236},
		// 85
		{80, 80, 80, 80, 80, 80, 80, 80, 80, 11: 80, 80, 14: 80, 16: 80, 21: 80, 81: 80},
		{17, 17, 17, 17, 17, 17, 17},
		{7: 230, 84, 12: 229, 23: 237},
		{8: 238},
		{81, 81, 81, 81, 81, 81, 81, 81, 81, 11: 81, 81, 14: 81, 16: 81, 21: 81, 81: 81},
		// 90
		{37, 37, 37, 37, 37, 37, 37},
		{34: 312},
		{34: 308},
		{34: 304},
		{34: 300},
		// 95
		{34: 294},
		{34: 288},
		{34: 282},
		{34: 276},
		{34: 270},
		// 100
		{34: 264},
		{34: 258},
		{34: 252},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 253},
		{16: 254},
		// 105
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 255},
		{16: 256},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 257},
		{19, 19, 19, 19, 19, 19, 19},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 259},
		// 110
		{16: 260},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 261},
		{16: 262},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 263},
		{20, 20, 20, 20, 20, 20, 20},
		// 115
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 265},
		{16: 266},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 267},
		{16: 268},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 269},
		// 120
		{21, 21, 21, 21, 21, 21, 21},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 271},
		{16: 272},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 273},
		{16: 274},
		// 125
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 275},
		{22, 22, 22, 22, 22, 22, 22},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 277},
		{16: 278},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 279},
		// 130
		{16: 280},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 281},
		{23, 23, 23, 23, 23, 23, 23},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 283},
		{16: 284},
		// 135
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 285},
		{16: 286},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 287},
		{24, 24, 24, 24, 24, 24, 24},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 289},
		// 140
		{16: 290},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 291},
		{16: 292},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 293},
		{25, 25, 25, 25, 25, 25, 25},
		// 145
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 295},
		{16: 296},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 297},
		{16: 298},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 299},
		// 150
		{26, 26, 26, 26, 26, 26, 26},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 301},
		{16: 302},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 303},
		{27, 27, 27, 27, 27, 27, 27},
		// 155
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 305},
		{16: 306},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 307},
		{28, 28, 28, 28, 28, 28, 28},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 309},
		// 160
		{16: 310},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 311},
		{29, 29, 29, 29, 29, 29, 29},
		{7: 211, 209, 212, 210, 13: 171, 16: 68, 18: 170, 313},
		{16: 314},
		// 165
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 315},
		{30, 30, 30, 30, 30, 30, 30},
		{46, 46, 46, 46, 46, 46, 46},
		{45, 45, 45, 45, 45, 45, 45},
		{44, 44, 44, 44, 44, 44, 44},
		// 170
		{43, 43, 43, 43, 43, 43, 43},
		{42, 42, 42, 42, 42, 42, 42},
		{41, 41, 41, 41, 41, 41, 41},
		{40, 40, 40, 40, 40, 40, 40},
		{39, 39, 39, 39, 39, 39, 39},
		// 175
		{38, 38, 38, 38, 38, 38, 38},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 327, 81: 3, 96: 326},
		{81: 329},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 327, 81: 3, 96: 328},
		{81: 4},
		// 180
		{51, 51, 51, 51, 51, 51, 51},
		{57, 57, 57, 57, 57, 57, 57},
		{56, 56, 56, 56, 56, 56, 56, 11: 332},
		{55, 55, 55, 55, 55, 55, 55},
		{58, 58, 58, 58, 58, 58, 58},
		// 185
		{59, 59, 59, 59, 59, 59, 59},
		{60, 60, 60, 60, 60, 60, 60},
		{61, 61, 61, 61, 61, 61, 61},
		{62, 62, 62, 62, 62, 62, 62},
		{63, 63, 63, 63, 63, 63, 63},
		// 190
		{64, 64, 64, 64, 64, 64, 64},
		{65, 65, 65, 65, 65, 65, 65},
		{66, 66, 66, 66, 66, 66, 66},
		{67, 67, 67, 67, 67, 67, 67},
		{9, 9, 9, 9, 9, 9, 9, 10: 69, 17: 344},
		// 195
		{7: 353, 358, 357, 11: 356, 229, 14: 359, 352, 23: 233, 25: 360, 355, 354, 351, 33: 350, 35: 349, 59: 348, 83: 347, 346, 345},
		{7, 7, 7, 7, 7, 7, 7, 20: 368},
		{129, 129, 129, 129, 129, 129, 129, 20: 129, 22: 371, 24: 129},
		{127, 127, 127, 127, 127, 127, 127, 15: 374, 17: 373, 20: 127, 22: 127, 24: 127},
		{124, 124, 124, 124, 124, 124, 124, 15: 124, 17: 124, 20: 124, 22: 124, 24: 124},
		// 200
		{119, 119, 119, 119, 119, 119, 119, 387, 12: 386, 15: 119, 17: 119, 20: 119, 22: 119, 24: 119, 29: 385, 384},
		{116, 116, 116, 116, 116, 116, 116, 116, 12: 116, 15: 116, 17: 116, 20: 116, 22: 116, 24: 116, 29: 116, 116, 381, 380},
		{113, 113, 113, 113, 113, 113, 113, 113, 12: 113, 15: 113, 17: 113, 20: 113, 22: 113, 24: 113, 29: 113, 113, 113, 113},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 379},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 367},
		// 205
		{110, 110, 110, 110, 110, 110, 110, 110, 12: 110, 15: 110, 17: 110, 20: 110, 22: 110, 24: 110, 29: 110, 110, 110, 110},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 348, 83: 347, 346, 362},
		{108, 108, 108, 108, 108, 108, 108, 108, 12: 108, 15: 108, 17: 108, 20: 108, 22: 108, 29: 108, 108, 108, 108},
		{8: 361},
		{106, 106, 106, 106, 106, 106, 106, 106, 12: 106, 15: 106, 17: 106, 20: 106, 22: 106, 29: 106, 106, 106, 106},
		// 210
		{105, 105, 105, 105, 105, 105, 105, 105, 12: 105, 15: 105, 17: 105, 20: 105, 22: 105, 29: 105, 105, 105, 105},
		{8, 8, 8, 8, 8, 8, 8},
		{107, 107, 107, 107, 107, 107, 107, 107, 12: 107, 15: 107, 17: 107, 20: 107, 22: 107, 24: 107, 29: 107, 107, 107, 107},
		{6: 369, 20: 368},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 367},
		// 215
		{108, 108, 108, 108, 108, 108, 108, 108, 12: 108, 15: 108, 17: 108, 20: 108, 22: 108, 24: 108, 29: 108, 108, 108, 108},
		{106, 106, 106, 106, 106, 106, 106, 106, 12: 106, 15: 106, 17: 106, 20: 106, 22: 106, 24: 106, 29: 106, 106, 106, 106},
		{105, 105, 105, 105, 105, 105, 105, 105, 12: 105, 15: 105, 17: 105, 20: 105, 22: 105, 24: 105, 29: 105, 105, 105, 105},
		{111, 111, 111, 111, 111, 111, 111, 111, 12: 111, 15: 111, 17: 111, 20: 111, 22: 111, 24: 111, 29: 111, 111, 111, 111},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 348, 83: 347, 370},
		// 220
		{109, 109, 109, 109, 109, 109, 109, 109, 12: 109, 15: 109, 17: 109, 20: 109, 22: 109, 24: 109, 29: 109, 109, 109, 109},
		{130, 130, 130, 130, 130, 130, 130, 20: 130, 22: 371, 24: 130},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 348, 83: 372},
		{128, 128, 128, 128, 128, 128, 128, 15: 374, 17: 373, 20: 128, 22: 128, 24: 128},
		{17: 377},
		// 225
		{17: 375},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 376},
		{125, 125, 125, 125, 125, 125, 125, 15: 125, 17: 125, 20: 125, 22: 125, 24: 125},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 378},
		{126, 126, 126, 126, 126, 126, 126, 15: 126, 17: 126, 20: 126, 22: 126, 24: 126},
		// 230
		{112, 112, 112, 112, 112, 112, 112, 112, 12: 112, 15: 112, 17: 112, 20: 112, 22: 112, 24: 112, 29: 112, 112, 112, 112},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 383},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 382},
		{114, 114, 114, 114, 114, 114, 114, 114, 12: 114, 15: 114, 17: 114, 20: 114, 22: 114, 24: 114, 29: 114, 114, 114, 114},
		{115, 115, 115, 115, 115, 115, 115, 115, 12: 115, 15: 115, 17: 115, 20: 115, 22: 115, 24: 115, 29: 115, 115, 115, 115},
		// 235
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 17: 394, 26: 355, 354, 351, 33: 350, 35: 393},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 17: 390, 26: 355, 354, 351, 33: 350, 35: 391},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 389},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 388},
		{117, 117, 117, 117, 117, 117, 117, 117, 12: 117, 15: 117, 17: 117, 20: 117, 22: 117, 24: 117, 29: 117, 117, 381, 380},
		// 240
		{118, 118, 118, 118, 118, 118, 118, 118, 12: 118, 15: 118, 17: 118, 20: 118, 22: 118, 24: 118, 29: 118, 118, 381, 380},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 392},
		{120, 120, 120, 120, 120, 120, 120, 387, 12: 386, 15: 120, 17: 120, 20: 120, 22: 120, 24: 120},
		{121, 121, 121, 121, 121, 121, 121, 387, 12: 386, 15: 121, 17: 121, 20: 121, 22: 121, 24: 121},
		{123, 123, 123, 123, 123, 123, 123, 387, 12: 386, 15: 123, 17: 123, 20: 123, 22: 123, 24: 123},
		// 245
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 395},
		{122, 122, 122, 122, 122, 122, 122, 387, 12: 386, 15: 122, 17: 122, 20: 122, 22: 122, 24: 122},
		{18, 18, 18, 18, 18, 18, 18},
		{34: 404},
		{34: 402},
		// 250
		{34: 400},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 401},
		{10, 10, 10, 10, 10, 10, 10},
		{68, 68, 68, 68, 68, 68, 68, 211, 209, 212, 210, 13: 171, 18: 170, 403},
		{11, 11, 11, 11, 11, 11, 11},
		// 255
		{8: 405},
		{17: 406},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 407},
		{12, 12, 12, 12, 12, 12, 12},
		{6: 409},
		// 260
		{89: 410},
		{1: 138, 4: 138, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 411, 161, 159, 82: 160},
		{1: 412},
		{2, 2, 2, 2, 2, 2, 2},
		{76, 76, 76, 76, 76, 76, 76, 10: 76, 76, 16: 76, 21: 76},
		// 265
		{95, 95, 95, 95, 95, 95, 95},
		{21: 417, 86: 416},
		{96, 96, 96, 96, 96, 96, 96},
		{17: 418},
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 419},
		// 270
		{78, 78, 78, 78, 78, 78, 78, 21: 417, 86: 420},
		{79, 79, 79, 79, 79, 79, 79},
		{98, 98, 98, 98, 98, 98, 98},
		{21: 417, 86: 431},
		{7: 94, 94, 94, 94, 13: 94, 21: 94},
		// 275
		{7: 93, 93, 93, 93, 13: 93, 21: 93},
		{7: 92, 92, 92, 92, 13: 92, 21: 92},
		{7: 91, 91, 91, 91, 13: 91, 21: 91},
		{7: 90, 90, 90, 90, 13: 90, 21: 90},
		{7: 89, 89, 89, 89, 13: 89, 21: 89},
		// 280
		{7: 88, 88, 88, 88, 13: 88, 21: 88},
		{7: 87, 87, 87, 87, 13: 87, 21: 87},
		{97, 97, 97, 97, 97, 97, 97},
		{7: 211, 209, 212, 210, 13: 171, 18: 170, 434, 21: 417, 86: 433},
		{100, 100, 100, 100, 100, 100, 100},
		// 285
		{21: 417, 86: 435},
		{99, 99, 99, 99, 99, 99, 99},
		{26: 452},
		{104: 438},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 348, 83: 347, 346, 439, 89: 440},
		// 290
		{4: 449, 20: 368},
		{11: 441},
		{10: 442},
		{10: 443},
		{11: 444},
		// 295
		{1: 445},
		{4: 446},
		{138, 4: 138, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 447, 161, 159, 82: 160},
		{448},
		{131, 131, 131, 131, 5: 131},
		// 300
		{138, 4: 138, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 450, 161, 159, 82: 160},
		{451},
		{132, 132, 132, 132, 5: 132},
		{8: 453},
		{17: 454},
		// 305
		{7: 230, 231, 11: 232, 229, 14: 234, 23: 233, 25: 455},
		{4: 456},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 348, 83: 347, 346, 457},
		{4: 458, 20: 368},
		{6: 138, 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 459, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204},
		// 310
		{6: 460},
		{6: 461},
		{4: 462},
		{138, 4: 138, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 463, 161, 159, 82: 160},
		{464},
		// 315
		{133, 133, 133, 133, 5: 133},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 348, 83: 347, 346, 466},
		{6: 467, 20: 368},
		{138, 4: 138, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 468, 161, 159, 82: 160},
		{469},
		// 320
		{134, 134, 134, 134, 5: 134},
		{7: 363, 365, 357, 11: 364, 14: 366, 352, 26: 355, 354, 351, 33: 350, 35: 349, 59: 348, 83: 347, 346, 471},
		{20: 368, 24: 472},
		{113: 473},
		{2: 138, 4: 138, 138, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 474, 161, 159, 82: 160},
		// 325
		{2: 475, 5: 476},
		{136, 136, 136, 136, 5: 136},
		{2: 138, 4: 138, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 477, 161, 159, 82: 160},
		{2: 478},
		{135, 135, 135, 135, 5: 135},
		// 330
		{147, 147, 147, 147, 5: 147},
		{144, 144, 144, 144, 138, 144, 7: 174, 172, 175, 173, 12: 195, 171, 17: 203, 170, 202, 36: 176, 166, 169, 167, 177, 191, 186, 168, 187, 157, 154, 162, 165, 163, 164, 199, 196, 200, 198, 156, 201, 197, 155, 60: 152, 188, 194, 193, 189, 180, 183, 182, 181, 179, 184, 185, 178, 190, 192, 204, 153, 158, 481, 161, 159, 82: 160},
		{146, 146, 146, 146, 5: 146},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 116

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			println("OGREE: Unrecognised command!")
cmd.WarningLogger.Println("Unknown Command")			/*yylex.Error(msg)*/
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			root = yyS[yypt-0].node
		}
	case 2:
		{
			yyVAL.node = &ast{BLOCK, []node{yyS[yypt-1].node}}
		}
	case 3:
		{
			yyVAL.node = &ast{BLOCK, []node{yyS[yypt-2].node, yyS[yypt-0].node}}
		}
	case 4:
		{
			yyVAL.node = &ast{IF, []node{yyS[yypt-0].node}}
		}
	case 7:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 8:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 9:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 10:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 11:
		{
			yyVAL.node = nil
		}
	case 12:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 13:
		{
			yyVAL.node = &ifNode{IF, yyS[yypt-4].node, yyS[yypt-1].node, nil}
		}
	case 14:
		{
			yyVAL.node = &ifNode{IF, yyS[yypt-6].node, yyS[yypt-3].node, yyS[yypt-1].node}
		}
	case 15:
		{
			yyVAL.node = &whileNode{WHILE, yyS[yypt-3].node, yyS[yypt-1].node}
		}
	case 16:
		{
			initnd := &assignNode{ASSIGN, yyS[yypt-11].s, dCatchNodePtr}
			yyVAL.node = &forNode{FOR, initnd, yyS[yypt-7].node, yyS[yypt-5].node, yyS[yypt-1].node}
		}
	case 17:
		{
			var incr *arithNode
			var incrAssign *assignNode
			n1 := &numNode{NUM, 0}

			initd := &assignNode{ASSIGN, yyS[yypt-5].s, n1}
			iter := &symbolReferenceNode{REFERENCE, yyS[yypt-5].s}
			cmp := &comparatorNode{COMPARATOR, "<", iter, yyS[yypt-3].node}
			incr = &arithNode{ARITHMETIC, "+", iter, &numNode{NUM, 1}}
			incrAssign = &assignNode{ASSIGN, iter, incr}
			yyVAL.node = &forNode{FOR, initd, cmp, incrAssign, yyS[yypt-1].node}

		}
	case 18:
		{
			n1 := &numNode{NUM, yyS[yypt-7].n}
			n2 := &numNode{NUM, yyS[yypt-4].n}
			initnd := &assignNode{ASSIGN, yyS[yypt-10].s, n1}
			var cond *comparatorNode
			var incr *arithNode
			var iter *symbolReferenceNode
			var incrAssign *assignNode

			iter = &symbolReferenceNode{NUM, yyS[yypt-10].s}

			if yyS[yypt-7].n < yyS[yypt-4].n {
				cond = &comparatorNode{COMPARATOR, "<", iter, n2}
				incr = &arithNode{ARITHMETIC, "+", iter, &numNode{NUM, 1}}
				incrAssign = &assignNode{ASSIGN, iter, incr} //Maybe redundant
			} else if yyS[yypt-7].n == yyS[yypt-4].n {

			} else { //$5 > 8
				cond = &comparatorNode{COMPARATOR, ">", iter, n2}
				incr = &arithNode{ARITHMETIC, "-", iter, &numNode{NUM, 1}}
				incrAssign = &assignNode{ASSIGN, iter, incr}
			}
			yyVAL.node = &forNode{FOR, initnd, cond, incrAssign, yyS[yypt-1].node}
		}
	case 22:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 23:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, "==", yyS[yypt-3].node, yyS[yypt-0].node}
		}
	case 24:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, "!=", yyS[yypt-3].node, yyS[yypt-0].node}
		}
	case 25:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 26:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, "<", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 27:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, "<=", yyS[yypt-3].node, yyS[yypt-0].node}
		}
	case 28:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, ">=", yyS[yypt-3].node, yyS[yypt-0].node}
		}
	case 29:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, ">", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 30:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 31:
		{
			yyVAL.node = &arithNode{ARITHMETIC, "+", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 32:
		{
			yyVAL.node = &arithNode{ARITHMETIC, "-", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 33:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 34:
		{
			yyVAL.node = &arithNode{ARITHMETIC, "*", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 35:
		{
			yyVAL.node = &arithNode{ARITHMETIC, "/", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 36:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 37:
		{
			yyVAL.node = &boolOpNode{BOOLOP, "!", yyS[yypt-0].node}
		}
	case 38:
		{
			left := &numNode{NUM, 0}
			yyVAL.node = &arithNode{ARITHMETIC, "-", left, yyS[yypt-0].node}
		}
	case 39:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 40:
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 41:
		{
			yyVAL.node = &numNode{NUM, yyS[yypt-0].n}
		}
	case 42:
		{
			yyVAL.node = &symbolReferenceNode{REFERENCE, yyS[yypt-0].s}
		}
	case 43:
		{
			yyVAL.node = &symbolReferenceNode{REFERENCE, yyS[yypt-0].s}
		}
	case 44:
		{
			var x bool
			if yyS[yypt-0].s == "false" {
				x = false
			} else {
				x = true
			}
			yyVAL.node = &boolNode{BOOL, x}
		}
	case 45:
		{
			println("@State start")
		}
	case 49:
		{
			yyVAL.node = &commonNode{COMMON, cmd.PostObj, "PostObj", []interface{}{cmd.EntityStrToInt(yyS[yypt-1].s), yyS[yypt-1].s, resMap(&yyS[yypt-0].s)}}
		}
	case 50:
		{
			cmd.Disp(resMap(&yyS[yypt-0].s))
			yyVAL.node = &commonNode{COMMON, cmd.PostObj, "PostObj", []interface{}{cmd.EntityStrToInt(yyS[yypt-2].s), yyS[yypt-2].s, resMap(&yyS[yypt-0].s)}}
		}
	case 51:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetObject, "GetObject", []interface{}{yyS[yypt-0].s}}
		}
	case 52:
		{ /*cmd.Disp(resMap(&$4)); */
			yyVAL.node = &commonNode{COMMON, cmd.SearchObjects, "SearchObjects", []interface{}{yyS[yypt-1].s, resMap(&yyS[yypt-0].s)}}
		}
	case 53:
		{
			yyVAL.node = &commonNode{COMMON, cmd.UpdateObj, "UpdateObj", []interface{}{yyS[yypt-1].s, resMap(&yyS[yypt-0].s)}}
		}
	case 54:
		{
			println("@State NT_DEL")
			yyVAL.node = &commonNode{COMMON, cmd.DeleteObj, "DeleteObj", []interface{}{yyS[yypt-0].s}}
		}
	case 63:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 64:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 65:
		{
			yyVAL.s = ""
		}
	case 66:
		{
			yyVAL.s = yyS[yypt-0].s
			dCatchPtr = yyS[yypt-0].s
			dCatchNodePtr = &strNode{STR, yyS[yypt-0].s}
		}
	case 67:
		{
			x := strconv.Itoa(yyS[yypt-0].n)
			yyVAL.s = x
			dCatchPtr = yyS[yypt-0].n
			dCatchNodePtr = &numNode{NUM, yyS[yypt-0].n}
		}
	case 68:
		{
			yyVAL.s = yyS[yypt-3].s + yyS[yypt-2].s + yyS[yypt-1].s + yyS[yypt-0].s
			dCatchPtr = yyS[yypt-3].s + yyS[yypt-2].s + yyS[yypt-1].s + yyS[yypt-0].s
			dCatchNodePtr = &strNode{STR, yyS[yypt-3].s + yyS[yypt-2].s + yyS[yypt-1].s + yyS[yypt-0].s}
		}
	case 69:
		{
			var x bool
			if yyS[yypt-0].s == "false" {
				x = false
			} else {
				x = true
			}
			dCatchPtr = x
			dCatchNodePtr = &boolNode{BOOL, x}
		}
	case 70:
		{
			yyVAL.s = string(yyS[yypt-3].s + "=" + yyS[yypt-1].s + "=" + yyS[yypt-0].s)
			println("So we got: ", yyVAL.s)
		}
	case 71:
		{
			yyVAL.s = yyS[yypt-2].s + "=" + yyS[yypt-0].s
		}
	case 73:
		{
			yyVAL.s = "/" + yyS[yypt-0].s
		}
	case 74:
		{
			yyVAL.s = yyS[yypt-2].s + "/" + yyS[yypt-0].s
		}
	case 75:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 76:
		{
			yyVAL.s = "../" + yyS[yypt-0].s
		}
	case 77:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 78:
		{
			yyVAL.s = ".."
		}
	case 79:
		{
			yyVAL.s = "-"
		}
	case 80:
		{
			yyVAL.s = ""
		}
	case 81:
		{
			yyVAL.s = ""
		}
	case 82:
		{ /*cmd.CD($2);*/
			yyVAL.node = &commonNode{COMMON, cmd.CD, "CD", []interface{}{yyS[yypt-0].s}}
		}
	case 83:
		{ /*cmd.LS($2)*/
			yyVAL.node = &commonNode{COMMON, cmd.LS, "LS", []interface{}{yyS[yypt-0].s}}
		}
	case 84:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 0}}
		}
	case 85:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 1}}
		}
	case 86:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 2}}
		}
	case 87:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 3}}
		}
	case 88:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 4}}
		}
	case 89:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 5}}
		}
	case 90:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 6}}
		}
	case 91:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 7}}
		}
	case 92:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Tree, "Tree", []interface{}{"", yyS[yypt-0].n}}
		}
	case 93:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Tree, "Tree", []interface{}{yyS[yypt-0].s, 0}}
		}
	case 94:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Tree, "Tree", []interface{}{yyS[yypt-1].s, yyS[yypt-0].n}}
		}
	case 95:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 96:
		{
			yyVAL.node = &commonNode{COMMON, nil, "CLR", nil}
		}
	case 97:
		{
			yyVAL.node = &commonNode{COMMON, nil, "Grep", nil}
		}
	case 98:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Print, "Print", []interface{}{yyS[yypt-1].s}}
		}
	case 99:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOG, "LSOG", nil}
		}
	case 100:
		{
			yyVAL.node = &commonNode{COMMON, cmd.PWD, "PWD", nil}
		}
	case 101:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Exit, "Exit", nil}
		}
	case 102:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{""}}
		}
	case 103:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"ls"}}
		}
	case 104:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"cd"}}
		}
	case 105:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"create"}}
		}
	case 106:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"gt"}}
		}
	case 107:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"update"}}
		}
	case 108:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"delete"}}
		}
	case 109:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{yyS[yypt-0].s}}
		}
	case 110:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"tree"}}
		}
	case 111:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"lsog"}}
		}
	case 112:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 113:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 114:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 115:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 116:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 117:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 118:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 119:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-2].s)), cmd.TENANT, map[string]interface{}{"attributes": map[string]interface{}{"color": yyS[yypt-0].s}}, rlPtr}}
		}
	case 120:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-2].s)), cmd.TENANT, map[string]interface{}{"attributes": map[string]interface{}{"color": yyS[yypt-0].s}}, rlPtr}}
		}
	case 121:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-2].s)), cmd.SITE, map[string]interface{}{"attributes": map[string]interface{}{"orientation": yyS[yypt-0].s}}, rlPtr}}
		}
	case 122:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-2].s)), cmd.SITE, map[string]interface{}{"attributes": map[string]interface{}{"orientation": yyS[yypt-0].s}}, rlPtr}}
		}
	case 123:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.BLDG, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 124:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.BLDG, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 125:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.ROOM, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 126:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.ROOM, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 127:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.RACK, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 128:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.RACK, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 129:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.DEVICE, map[string]interface{}{"attributes": map[string]interface{}{"slot": yyS[yypt-2].s, "sizeUnit": yyS[yypt-0].s}}, rlPtr}}
		}
	case 130:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.DEVICE, map[string]interface{}{"attributes": map[string]interface{}{"slot": yyS[yypt-2].s, "sizeUnit": yyS[yypt-0].s}}, rlPtr}}
		}
	case 131:
		{
			yyVAL.node = &commonNode{COMMON, cmd.DeleteObj, "DeleteObj", []interface{}{replaceOCLICurrPath(yyS[yypt-0].s)}}
		}
	case 132:
		{
			val := yyS[yypt-2].s + "=" + yyS[yypt-0].s
			yyVAL.node = &commonNode{COMMON, cmd.UpdateObj, "UpdateObj", []interface{}{replaceOCLICurrPath(yyS[yypt-4].s), resMap(&val)}}
			println("Attribute Acquired")
		}
	case 133:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetObject, "GetObject", []interface{}{replaceOCLICurrPath(yyS[yypt-0].s)}}
		}
	case 134:
		{
			x := make([]string, 0)
			x = append(x, cmd.State.CurrPath+"/"+yyS[yypt-2].s)
			x = append(x, yyS[yypt-0].sarr...)
			yyVAL.sarr = x
		}
	case 135:
		{
			yyVAL.sarr = []string{cmd.State.CurrPath + "/" + yyS[yypt-0].s}
		}
	case 136:
		{
			yyVAL.node = &commonNode{COMMON, cmd.SetClipBoard, "setCB", []interface{}{&yyS[yypt-1].sarr}}
			println("Selection made!")
		}
	case 137:
		{
			yyVAL.node = &assignNode{ASSIGN, yyS[yypt-2].s, dCatchNodePtr}
		}
	case 138:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LoadFile, "Load", []interface{}{yyS[yypt-0].s}}
		}
	case 139:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LoadFile, "Load", []interface{}{yyS[yypt-0].s}}
		}
	case 140:
		{
			yyVAL.node = &symbolReferenceNode{REFERENCE, yyS[yypt-0].s}
		}
	case 141:
		{
			n := &symbolReferenceNode{REFERENCE, yyS[yypt-2].s}
			yyVAL.node = &assignNode{ASSIGN, n, dCatchNodePtr}
		}
	case 142:
		{
			n := &symbolReferenceNode{REFERENCE, yyS[yypt-2].s}
			yyVAL.node = &assignNode{ASSIGN, n, yyS[yypt-0].node}
		}
	case 143:
		{
			yyVAL.node = &commonNode{COMMON, cmd.ShowClipBoard, "select", nil}
		}
	case 144:
		{
			x := yyS[yypt-2].s + "=" + yyS[yypt-0].s
			yyVAL.node = &commonNode{COMMON, cmd.UpdateSelection, "UpdateSelect", []interface{}{resMap(&x)}}
		}
	case 145:
		{
			yyVAL.s = yyS[yypt-1].s + " " + yyS[yypt-0].s
		}
	case 146:
		{
			yyVAL.s = ""
		}
	case 147:
		{
			yyVAL.node = nil
			funcTable[yyS[yypt-5].s] = &funcNode{FUNC, yyS[yypt-1].node}
		}
	case 148:
		{
			x := funcTable[yyS[yypt-0].s]
			if _, ok := x.(node); ok {
				yyVAL.node = x.(node)
			} else {
				yyVAL.node = nil
			}
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
