// Code generated by goyacc - DO NOT EDIT.

package main

import __yyfmt__ "fmt"

import (
	cmd "cli/controllers"
	"strconv"
	"strings"
)

var root node

func resMap(x *string) map[string]interface{} {
	resarr := strings.Split(*x, "=")
	res := make(map[string]interface{})
	attrs := make(map[string]string)

	for i := 0; i+1 < len(resarr); {
		if i+1 < len(resarr) {
			switch resarr[i] {
			case "id", "name", "category", "parentID",
				"description", "domain", "parentid", "parentId":
				res[resarr[i]] = resarr[i+1]

			default:
				attrs[resarr[i]] = resarr[i+1]
			}
			i += 2
		}
	}
	res["attributes"] = attrs
	return res
}

func replaceOCLICurrPath(x string) string {
	return strings.Replace(x, "_", cmd.State.CurrPath, 1)
}

type yySymType struct {
	yys     int
	n       int
	s       string
	sarr    []string
	ast     *ast
	node    node
	nodeArr []node
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault      = 57425
	yyEofCode      = 57344
	TOK_AND        = 57415
	TOK_ATTR       = 57356
	TOK_ATTRSPEC   = 57390
	TOK_BASHTYPE   = 57365
	TOK_BLDG       = 57350
	TOK_BOOL       = 57359
	TOK_CD         = 57371
	TOK_CLR        = 57373
	TOK_CMDFLAG    = 57367
	TOK_CMDS       = 57401
	TOK_COMMA      = 57399
	TOK_CREATE     = 57360
	TOK_DELETE     = 57363
	TOK_DEREF      = 57404
	TOK_DEVICE     = 57353
	TOK_DIV        = 57418
	TOK_DOC        = 57370
	TOK_DONE       = 57424
	TOK_DOT        = 57400
	TOK_ELSE       = 57409
	TOK_EQUAL      = 57366
	TOK_EXIT       = 57369
	TOK_FI         = 57423
	TOK_FOR        = 57407
	TOK_GET        = 57361
	TOK_GREATER    = 57420
	TOK_GREP       = 57374
	TOK_IF         = 57406
	TOK_IN         = 57416
	TOK_LBLOCK     = 57410
	TOK_LBRAC      = 57397
	TOK_LESS       = 57421
	TOK_LPAREN     = 57412
	TOK_LS         = 57375
	TOK_LSBLDG     = 57380
	TOK_LSDEV      = 57383
	TOK_LSOG       = 57377
	TOK_LSRACK     = 57382
	TOK_LSROOM     = 57381
	TOK_LSSITE     = 57379
	TOK_LSSUBDEV   = 57384
	TOK_LSSUBDEV1  = 57385
	TOK_LSTEN      = 57378
	TOK_MULT       = 57419
	TOK_NOT        = 57417
	TOK_NUM        = 57346
	TOK_OCBLDG     = 57386
	TOK_OCDEL      = 57358
	TOK_OCDEV      = 57387
	TOK_OCPSPEC    = 57395
	TOK_OCRACK     = 57388
	TOK_OCROOM     = 57389
	TOK_OCSDEV     = 57393
	TOK_OCSDEV1    = 57394
	TOK_OCSITE     = 57391
	TOK_OCTENANT   = 57392
	TOK_OR         = 57414
	TOK_PLUS       = 57357
	TOK_PWD        = 57372
	TOK_RACK       = 57352
	TOK_RBLOCK     = 57411
	TOK_RBRAC      = 57398
	TOK_ROOM       = 57351
	TOK_RPAREN     = 57413
	TOK_SEARCH     = 57364
	TOK_SELECT     = 57396
	TOK_SEMICOL    = 57405
	TOK_SITE       = 57349
	TOK_SLASH      = 57368
	TOK_SUBDEVICE  = 57354
	TOK_SUBDEVICE1 = 57355
	TOK_TEMPLATE   = 57402
	TOK_TENANT     = 57348
	TOK_THEN       = 57422
	TOK_TREE       = 57376
	TOK_UPDATE     = 57362
	TOK_VAR        = 57403
	TOK_WHILE      = 57408
	TOK_WORD       = 57347
	yyErrCode      = 57345

	yyMaxDepth = 200
	yyTabOfs   = -139
)

var (
	yyPrec = map[int]int{
		TOK_MULT:  0,
		TOK_OCDEL: 0,
		TOK_DIV:   0,
		TOK_PLUS:  0,
		TOK_EQUAL: 1,
	}

	yyXLAT = map[int]int{
		57405: 0,   // TOK_SEMICOL (142x)
		57413: 1,   // TOK_RPAREN (135x)
		57424: 2,   // TOK_DONE (122x)
		57423: 3,   // TOK_FI (120x)
		57344: 4,   // $end (119x)
		57409: 5,   // TOK_ELSE (118x)
		57358: 6,   // TOK_OCDEL (111x)
		57347: 7,   // TOK_WORD (106x)
		57400: 8,   // TOK_DOT (65x)
		57346: 9,   // TOK_NUM (57x)
		57357: 10,  // TOK_PLUS (51x)
		57404: 11,  // TOK_DEREF (50x)
		57368: 12,  // TOK_SLASH (49x)
		57390: 13,  // TOK_ATTRSPEC (47x)
		57450: 14,  // P1 (42x)
		57359: 15,  // TOK_BOOL (42x)
		57417: 16,  // TOK_NOT (41x)
		57366: 17,  // TOK_EQUAL (40x)
		57449: 18,  // P (39x)
		57356: 19,  // TOK_ATTR (31x)
		57414: 20,  // TOK_OR (29x)
		57411: 21,  // TOK_RBLOCK (26x)
		57448: 22,  // ORIENTN (25x)
		57415: 23,  // TOK_AND (25x)
		57453: 24,  // WORDORNUM (24x)
		57412: 25,  // TOK_LPAREN (21x)
		57454: 26,  // factor (18x)
		57461: 27,  // unary (18x)
		57395: 28,  // TOK_OCPSPEC (15x)
		57460: 29,  // term (14x)
		57420: 30,  // TOK_GREATER (14x)
		57421: 31,  // TOK_LESS (14x)
		57418: 32,  // TOK_DIV (13x)
		57419: 33,  // TOK_MULT (13x)
		57455: 34,  // nex (12x)
		57371: 35,  // TOK_CD (9x)
		57360: 36,  // TOK_CREATE (9x)
		57363: 37,  // TOK_DELETE (9x)
		57361: 38,  // TOK_GET (9x)
		57375: 39,  // TOK_LS (9x)
		57377: 40,  // TOK_LSOG (9x)
		57376: 41,  // TOK_TREE (9x)
		57362: 42,  // TOK_UPDATE (9x)
		57426: 43,  // BASH (8x)
		57434: 44,  // K (8x)
		57435: 45,  // NT_CREATE (8x)
		57436: 46,  // NT_DEL (8x)
		57437: 47,  // NT_GET (8x)
		57438: 48,  // NT_UPDATE (8x)
		57439: 49,  // OCCHOOSE (8x)
		57441: 50,  // OCDEL (8x)
		57442: 51,  // OCDOT (8x)
		57443: 52,  // OCGET (8x)
		57444: 53,  // OCLISYNTX (8x)
		57445: 54,  // OCSEL (8x)
		57446: 55,  // OCUPDATE (8x)
		57451: 56,  // Q (8x)
		57452: 57,  // REL (8x)
		57459: 58,  // stmnt (8x)
		57373: 59,  // TOK_CLR (8x)
		57370: 60,  // TOK_DOC (8x)
		57369: 61,  // TOK_EXIT (8x)
		57374: 62,  // TOK_GREP (8x)
		57380: 63,  // TOK_LSBLDG (8x)
		57383: 64,  // TOK_LSDEV (8x)
		57382: 65,  // TOK_LSRACK (8x)
		57381: 66,  // TOK_LSROOM (8x)
		57379: 67,  // TOK_LSSITE (8x)
		57384: 68,  // TOK_LSSUBDEV (8x)
		57385: 69,  // TOK_LSSUBDEV1 (8x)
		57378: 70,  // TOK_LSTEN (8x)
		57372: 71,  // TOK_PWD (8x)
		57396: 72,  // TOK_SELECT (8x)
		57427: 73,  // CTRL (7x)
		57447: 74,  // OPEN_STMT (7x)
		57457: 75,  // st2 (7x)
		57407: 76,  // TOK_FOR (7x)
		57406: 77,  // TOK_IF (7x)
		57408: 78,  // TOK_WHILE (7x)
		57429: 79,  // EQAL (6x)
		57431: 80,  // F (5x)
		57433: 81,  // JOIN (5x)
		57430: 82,  // EXPR (4x)
		57398: 83,  // TOK_RBRAC (4x)
		57350: 84,  // TOK_BLDG (3x)
		57353: 85,  // TOK_DEVICE (3x)
		57352: 86,  // TOK_RACK (3x)
		57351: 87,  // TOK_ROOM (3x)
		57349: 88,  // TOK_SITE (3x)
		57348: 89,  // TOK_TENANT (3x)
		57428: 90,  // E (2x)
		57432: 91,  // GETOBJS (2x)
		57397: 92,  // TOK_LBRAC (2x)
		57354: 93,  // TOK_SUBDEVICE (2x)
		57355: 94,  // TOK_SUBDEVICE1 (2x)
		57440: 95,  // OCCR (1x)
		57456: 96,  // opn (1x)
		57458: 97,  // start (1x)
		57401: 98,  // TOK_CMDS (1x)
		57399: 99,  // TOK_COMMA (1x)
		57416: 100, // TOK_IN (1x)
		57410: 101, // TOK_LBLOCK (1x)
		57386: 102, // TOK_OCBLDG (1x)
		57387: 103, // TOK_OCDEV (1x)
		57388: 104, // TOK_OCRACK (1x)
		57389: 105, // TOK_OCROOM (1x)
		57391: 106, // TOK_OCSITE (1x)
		57392: 107, // TOK_OCTENANT (1x)
		57402: 108, // TOK_TEMPLATE (1x)
		57422: 109, // TOK_THEN (1x)
		57403: 110, // TOK_VAR (1x)
		57425: 111, // $default (0x)
		57345: 112, // error (0x)
		57365: 113, // TOK_BASHTYPE (0x)
		57367: 114, // TOK_CMDFLAG (0x)
		57393: 115, // TOK_OCSDEV (0x)
		57394: 116, // TOK_OCSDEV1 (0x)
		57364: 117, // TOK_SEARCH (0x)
	}

	yySymNames = []string{
		"TOK_SEMICOL",
		"TOK_RPAREN",
		"TOK_DONE",
		"TOK_FI",
		"$end",
		"TOK_ELSE",
		"TOK_OCDEL",
		"TOK_WORD",
		"TOK_DOT",
		"TOK_NUM",
		"TOK_PLUS",
		"TOK_DEREF",
		"TOK_SLASH",
		"TOK_ATTRSPEC",
		"P1",
		"TOK_BOOL",
		"TOK_NOT",
		"TOK_EQUAL",
		"P",
		"TOK_ATTR",
		"TOK_OR",
		"TOK_RBLOCK",
		"ORIENTN",
		"TOK_AND",
		"WORDORNUM",
		"TOK_LPAREN",
		"factor",
		"unary",
		"TOK_OCPSPEC",
		"term",
		"TOK_GREATER",
		"TOK_LESS",
		"TOK_DIV",
		"TOK_MULT",
		"nex",
		"TOK_CD",
		"TOK_CREATE",
		"TOK_DELETE",
		"TOK_GET",
		"TOK_LS",
		"TOK_LSOG",
		"TOK_TREE",
		"TOK_UPDATE",
		"BASH",
		"K",
		"NT_CREATE",
		"NT_DEL",
		"NT_GET",
		"NT_UPDATE",
		"OCCHOOSE",
		"OCDEL",
		"OCDOT",
		"OCGET",
		"OCLISYNTX",
		"OCSEL",
		"OCUPDATE",
		"Q",
		"REL",
		"stmnt",
		"TOK_CLR",
		"TOK_DOC",
		"TOK_EXIT",
		"TOK_GREP",
		"TOK_LSBLDG",
		"TOK_LSDEV",
		"TOK_LSRACK",
		"TOK_LSROOM",
		"TOK_LSSITE",
		"TOK_LSSUBDEV",
		"TOK_LSSUBDEV1",
		"TOK_LSTEN",
		"TOK_PWD",
		"TOK_SELECT",
		"CTRL",
		"OPEN_STMT",
		"st2",
		"TOK_FOR",
		"TOK_IF",
		"TOK_WHILE",
		"EQAL",
		"F",
		"JOIN",
		"EXPR",
		"TOK_RBRAC",
		"TOK_BLDG",
		"TOK_DEVICE",
		"TOK_RACK",
		"TOK_ROOM",
		"TOK_SITE",
		"TOK_TENANT",
		"E",
		"GETOBJS",
		"TOK_LBRAC",
		"TOK_SUBDEVICE",
		"TOK_SUBDEVICE1",
		"OCCR",
		"opn",
		"start",
		"TOK_CMDS",
		"TOK_COMMA",
		"TOK_IN",
		"TOK_LBLOCK",
		"TOK_OCBLDG",
		"TOK_OCDEV",
		"TOK_OCRACK",
		"TOK_OCROOM",
		"TOK_OCSITE",
		"TOK_OCTENANT",
		"TOK_TEMPLATE",
		"TOK_THEN",
		"TOK_VAR",
		"$default",
		"error",
		"TOK_BASHTYPE",
		"TOK_CMDFLAG",
		"TOK_OCSDEV",
		"TOK_OCSDEV1",
		"TOK_SEARCH",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:   {0, 1},
		1:   {97, 1},
		2:   {75, 2},
		3:   {75, 3},
		4:   {75, 1},
		5:   {96, 1},
		6:   {96, 0},
		7:   {58, 1},
		8:   {58, 1},
		9:   {58, 1},
		10:  {58, 0},
		11:  {73, 1},
		12:  {74, 7},
		13:  {74, 9},
		14:  {74, 6},
		15:  {74, 15},
		16:  {74, 12},
		17:  {82, 3},
		18:  {82, 1},
		19:  {81, 3},
		20:  {81, 1},
		21:  {79, 4},
		22:  {79, 4},
		23:  {79, 1},
		24:  {57, 3},
		25:  {57, 4},
		26:  {57, 4},
		27:  {57, 3},
		28:  {57, 1},
		29:  {34, 3},
		30:  {34, 3},
		31:  {34, 1},
		32:  {29, 3},
		33:  {29, 3},
		34:  {29, 1},
		35:  {27, 2},
		36:  {27, 2},
		37:  {27, 1},
		38:  {26, 3},
		39:  {26, 1},
		40:  {26, 1},
		41:  {26, 1},
		42:  {44, 1},
		43:  {44, 1},
		44:  {44, 1},
		45:  {44, 1},
		46:  {45, 3},
		47:  {45, 4},
		48:  {47, 2},
		49:  {47, 3},
		50:  {48, 3},
		51:  {46, 2},
		52:  {90, 1},
		53:  {90, 1},
		54:  {90, 1},
		55:  {90, 1},
		56:  {90, 1},
		57:  {90, 1},
		58:  {90, 1},
		59:  {90, 1},
		60:  {22, 1},
		61:  {22, 1},
		62:  {22, 0},
		63:  {24, 1},
		64:  {24, 1},
		65:  {24, 4},
		66:  {24, 1},
		67:  {80, 4},
		68:  {80, 3},
		69:  {18, 1},
		70:  {18, 2},
		71:  {14, 3},
		72:  {14, 1},
		73:  {14, 4},
		74:  {14, 1},
		75:  {14, 2},
		76:  {14, 1},
		77:  {14, 2},
		78:  {14, 0},
		79:  {56, 2},
		80:  {56, 2},
		81:  {56, 2},
		82:  {56, 2},
		83:  {56, 2},
		84:  {56, 2},
		85:  {56, 2},
		86:  {56, 2},
		87:  {56, 2},
		88:  {56, 2},
		89:  {56, 2},
		90:  {56, 2},
		91:  {56, 3},
		92:  {56, 1},
		93:  {43, 1},
		94:  {43, 1},
		95:  {43, 1},
		96:  {43, 1},
		97:  {43, 1},
		98:  {43, 1},
		99:  {43, 2},
		100: {43, 2},
		101: {43, 2},
		102: {43, 2},
		103: {43, 2},
		104: {43, 2},
		105: {43, 2},
		106: {43, 2},
		107: {43, 2},
		108: {53, 2},
		109: {53, 1},
		110: {53, 1},
		111: {53, 1},
		112: {53, 1},
		113: {53, 1},
		114: {53, 1},
		115: {95, 5},
		116: {95, 5},
		117: {95, 5},
		118: {95, 5},
		119: {95, 7},
		120: {95, 7},
		121: {95, 7},
		122: {95, 7},
		123: {95, 7},
		124: {95, 7},
		125: {95, 7},
		126: {95, 7},
		127: {50, 2},
		128: {55, 5},
		129: {52, 2},
		130: {91, 3},
		131: {91, 1},
		132: {49, 4},
		133: {51, 6},
		134: {51, 4},
		135: {51, 4},
		136: {51, 2},
		137: {54, 1},
		138: {54, 5},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [307][]uint16{
		// 0
		{129, 4: 129, 6: 163, 161, 162, 10: 183, 164, 160, 14: 159, 17: 191, 190, 35: 165, 155, 158, 156, 166, 179, 175, 157, 176, 144, 151, 154, 152, 153, 187, 184, 188, 186, 146, 189, 185, 145, 58: 142, 177, 182, 181, 178, 169, 172, 171, 170, 168, 173, 174, 167, 180, 192, 143, 147, 141, 150, 148, 149, 97: 140},
		{4: 139},
		{4: 138},
		{444, 2: 133, 133, 133, 133, 96: 443},
		{2: 135, 135, 135, 135},
		// 5
		{132, 132, 132, 132, 132, 132},
		{131, 131, 131, 131, 131, 131},
		{130, 130, 130, 130, 130, 130},
		{2: 128, 128, 128, 128},
		{101: 434},
		// 10
		{25: 429},
		{7: 362, 25: 361},
		{97, 97, 97, 97, 97, 97},
		{96, 96, 96, 96, 96, 96},
		{95, 95, 95, 95, 95, 95},
		// 15
		{94, 94, 94, 94, 94, 94},
		{84: 350, 353, 352, 351, 349, 348, 357, 93: 354, 355},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 346, 84: 350, 353, 352, 351, 349, 348, 347, 93: 354, 355},
		{6: 198, 161, 197, 11: 199, 160, 14: 159, 18: 340, 61},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 339},
		// 20
		{70, 70, 70, 70, 70, 70, 8: 70, 70, 13: 70, 19: 70},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 61, 11: 199, 13: 61, 338, 19: 61},
		{67, 67, 67, 67, 67, 67, 8: 67, 67, 12: 336, 67, 19: 67},
		{8: 208, 98: 326, 108: 327, 110: 325},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 324},
		// 25
		{7: 323},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 322},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 321},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 320},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 319},
		// 30
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 318},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 317},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 316},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 315},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 314},
		// 35
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 313},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 310, 11: 199, 160, 14: 159, 18: 311},
		{47, 47, 47, 47, 47, 47},
		{46, 46, 46, 46, 46, 46},
		{45, 45, 45, 45, 45, 45},
		// 40
		{44, 44, 44, 44, 44, 44},
		{43, 43, 43, 43, 43, 43},
		{42, 42, 42, 42, 42, 42},
		{41, 41, 41, 41, 41, 41, 7: 307, 35: 302, 303, 306, 304, 301, 309, 308, 305},
		{84: 230, 236, 234, 232, 228, 226, 95: 224, 102: 229, 235, 233, 231, 227, 225},
		// 45
		{30, 30, 30, 30, 30, 30},
		{29, 29, 29, 29, 29, 29},
		{28, 28, 28, 28, 28, 28},
		{27, 27, 27, 27, 27, 27},
		{26, 26, 26, 26, 26, 26},
		// 50
		{25, 25, 25, 25, 25, 25},
		{8: 211},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 200, 92: 201},
		{2, 2, 2, 2, 2, 2, 8: 193},
		{19: 194},
		// 55
		{17: 195},
		{7: 196},
		{1, 1, 1, 1, 1, 1},
		{8: 208},
		{63, 63, 63, 63, 63, 63, 8: 63, 63, 13: 63, 19: 63},
		// 60
		{7: 207},
		{10, 10, 10, 10, 10, 10},
		{7: 202, 91: 203},
		{83: 8, 99: 205},
		{83: 204},
		// 65
		{7, 7, 7, 7, 7, 7},
		{7: 202, 91: 206},
		{83: 9},
		{62, 62, 62, 62, 62, 62, 8: 62, 62, 13: 62, 19: 62},
		{64, 64, 64, 64, 64, 64, 8: 64, 64, 12: 209, 64, 19: 64},
		// 70
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 61, 11: 199, 13: 61, 210, 19: 61},
		{66, 66, 66, 66, 66, 66, 8: 66, 66, 13: 66, 19: 66},
		{19: 212},
		{17: 213},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 220},
		// 75
		{7: 79},
		{7: 78},
		{76, 76, 76, 76, 76, 76, 13: 76, 19: 76},
		{75, 75, 75, 75, 75, 75, 13: 75, 19: 75},
		{7: 221},
		// 80
		{73, 73, 73, 73, 73, 73, 13: 73, 19: 73},
		{11, 11, 11, 11, 11, 11},
		{6: 215, 77, 10: 214, 22: 222},
		{7: 223},
		{74, 74, 74, 74, 74, 74, 13: 74, 19: 74},
		// 85
		{31, 31, 31, 31, 31, 31},
		{28: 297},
		{28: 293},
		{28: 289},
		{28: 285},
		// 90
		{28: 279},
		{28: 273},
		{28: 267},
		{28: 261},
		{28: 255},
		// 95
		{28: 249},
		{28: 243},
		{28: 237},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 238},
		{13: 239},
		// 100
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 240},
		{13: 241},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 242},
		{13, 13, 13, 13, 13, 13},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 244},
		// 105
		{13: 245},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 246},
		{13: 247},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 248},
		{14, 14, 14, 14, 14, 14},
		// 110
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 250},
		{13: 251},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 252},
		{13: 253},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 254},
		// 115
		{15, 15, 15, 15, 15, 15},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 256},
		{13: 257},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 258},
		{13: 259},
		// 120
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 260},
		{16, 16, 16, 16, 16, 16},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 262},
		{13: 263},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 264},
		// 125
		{13: 265},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 266},
		{17, 17, 17, 17, 17, 17},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 268},
		{13: 269},
		// 130
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 270},
		{13: 271},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 272},
		{18, 18, 18, 18, 18, 18},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 274},
		// 135
		{13: 275},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 276},
		{13: 277},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 278},
		{19, 19, 19, 19, 19, 19},
		// 140
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 280},
		{13: 281},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 282},
		{13: 283},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 284},
		// 145
		{20, 20, 20, 20, 20, 20},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 286},
		{13: 287},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 288},
		{21, 21, 21, 21, 21, 21},
		// 150
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 290},
		{13: 291},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 292},
		{22, 22, 22, 22, 22, 22},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 294},
		// 155
		{13: 295},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 296},
		{23, 23, 23, 23, 23, 23},
		{6: 198, 161, 197, 11: 199, 160, 61, 159, 18: 298},
		{13: 299},
		// 160
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 300},
		{24, 24, 24, 24, 24, 24},
		{40, 40, 40, 40, 40, 40},
		{39, 39, 39, 39, 39, 39},
		{38, 38, 38, 38, 38, 38},
		// 165
		{37, 37, 37, 37, 37, 37},
		{36, 36, 36, 36, 36, 36},
		{35, 35, 35, 35, 35, 35},
		{34, 34, 34, 34, 34, 34},
		{33, 33, 33, 33, 33, 33},
		// 170
		{32, 32, 32, 32, 32, 32},
		{50, 50, 50, 50, 50, 50},
		{49, 49, 49, 49, 49, 49, 9: 312},
		{48, 48, 48, 48, 48, 48},
		{51, 51, 51, 51, 51, 51},
		// 175
		{52, 52, 52, 52, 52, 52},
		{53, 53, 53, 53, 53, 53},
		{54, 54, 54, 54, 54, 54},
		{55, 55, 55, 55, 55, 55},
		{56, 56, 56, 56, 56, 56},
		// 180
		{57, 57, 57, 57, 57, 57},
		{58, 58, 58, 58, 58, 58},
		{59, 59, 59, 59, 59, 59},
		{60, 60, 60, 60, 60, 60},
		{3, 3, 3, 3, 3, 3, 8: 62},
		// 185
		{12, 12, 12, 12, 12, 12},
		{28: 332},
		{28: 330},
		{28: 328},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 329},
		// 190
		{4, 4, 4, 4, 4, 4},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 11: 199, 160, 14: 159, 18: 331},
		{5, 5, 5, 5, 5, 5},
		{7: 333},
		{17: 334},
		// 195
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 335},
		{6, 6, 6, 6, 6, 6},
		{61, 61, 61, 61, 61, 61, 198, 161, 197, 61, 11: 199, 13: 61, 337, 19: 61},
		{68, 68, 68, 68, 68, 68, 8: 68, 68, 13: 68, 19: 68},
		{69, 69, 69, 69, 69, 69, 8: 69, 69, 13: 69, 19: 69},
		// 200
		{88, 88, 88, 88, 88, 88},
		{19: 342, 80: 341},
		{89, 89, 89, 89, 89, 89},
		{17: 343},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 344},
		// 205
		{71, 71, 71, 71, 71, 71, 19: 342, 80: 345},
		{72, 72, 72, 72, 72, 72},
		{91, 91, 91, 91, 91, 91},
		{19: 342, 80: 356},
		{6: 87, 87, 87, 11: 87, 87, 19: 87},
		// 210
		{6: 86, 86, 86, 11: 86, 86, 19: 86},
		{6: 85, 85, 85, 11: 85, 85, 19: 85},
		{6: 84, 84, 84, 11: 84, 84, 19: 84},
		{6: 83, 83, 83, 11: 83, 83, 19: 83},
		{6: 82, 82, 82, 11: 82, 82, 19: 82},
		// 215
		{6: 81, 81, 81, 11: 81, 81, 19: 81},
		{6: 80, 80, 80, 11: 80, 80, 19: 80},
		{90, 90, 90, 90, 90, 90},
		{6: 198, 161, 197, 11: 199, 160, 14: 159, 18: 359, 342, 80: 358},
		{93, 93, 93, 93, 93, 93},
		// 220
		{19: 342, 80: 360},
		{92, 92, 92, 92, 92, 92},
		{25: 373},
		{100: 363},
		{92: 364},
		// 225
		{9: 365},
		{8: 366},
		{8: 367},
		{9: 368},
		{83: 369},
		// 230
		{370},
		{129, 2: 129, 6: 163, 161, 162, 10: 183, 164, 160, 14: 159, 17: 191, 190, 35: 165, 155, 158, 156, 166, 179, 175, 157, 176, 144, 151, 154, 152, 153, 187, 184, 188, 186, 146, 189, 185, 145, 58: 142, 177, 182, 181, 178, 169, 172, 171, 170, 168, 173, 174, 167, 180, 192, 143, 147, 371, 150, 148, 149},
		{2: 372},
		{2: 123, 123, 123, 123},
		{7: 374},
		// 235
		{17: 375},
		{6: 215, 216, 9: 217, 214, 15: 219, 22: 218, 24: 376},
		{377},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 382, 57: 381, 79: 380, 81: 379, 378},
		{422, 20: 393},
		// 240
		{121, 121, 20: 121, 121, 23: 396},
		{119, 119, 16: 399, 398, 20: 119, 119, 23: 119},
		{116, 116, 16: 116, 116, 20: 116, 116, 23: 116},
		{111, 111, 6: 413, 10: 412, 16: 111, 111, 20: 111, 111, 23: 111, 30: 411, 410},
		{108, 108, 6: 108, 10: 108, 16: 108, 108, 20: 108, 108, 23: 108, 30: 108, 108, 407, 406},
		// 245
		{105, 105, 6: 105, 10: 105, 16: 105, 105, 20: 105, 105, 23: 105, 30: 105, 105, 105, 105},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 405},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 404},
		{102, 102, 6: 102, 10: 102, 16: 102, 102, 20: 102, 102, 23: 102, 30: 102, 102, 102, 102},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 382, 57: 381, 79: 380, 81: 379, 392},
		// 250
		{100, 100, 6: 100, 10: 100, 16: 100, 100, 20: 100, 100, 23: 100, 30: 100, 100, 100, 100},
		{99, 99, 6: 99, 10: 99, 16: 99, 99, 20: 99, 99, 23: 99, 30: 99, 99, 99, 99},
		{98, 98, 6: 98, 10: 98, 16: 98, 98, 20: 98, 98, 23: 98, 30: 98, 98, 98, 98},
		{1: 394, 20: 393},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 382, 57: 381, 79: 380, 81: 395},
		// 255
		{101, 101, 6: 101, 10: 101, 16: 101, 101, 20: 101, 101, 23: 101, 30: 101, 101, 101, 101},
		{122, 122, 20: 122, 122, 23: 396},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 382, 57: 381, 79: 397},
		{120, 120, 16: 399, 398, 20: 120, 120, 23: 120},
		{17: 402},
		// 260
		{17: 400},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 382, 57: 401},
		{117, 117, 16: 117, 117, 20: 117, 117, 23: 117},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 382, 57: 403},
		{118, 118, 16: 118, 118, 20: 118, 118, 23: 118},
		// 265
		{103, 103, 6: 103, 10: 103, 16: 103, 103, 20: 103, 103, 23: 103, 30: 103, 103, 103, 103},
		{104, 104, 6: 104, 10: 104, 16: 104, 104, 20: 104, 104, 23: 104, 30: 104, 104, 104, 104},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 409},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 408},
		{106, 106, 6: 106, 10: 106, 16: 106, 106, 20: 106, 106, 23: 106, 30: 106, 106, 106, 106},
		// 270
		{107, 107, 6: 107, 10: 107, 16: 107, 107, 20: 107, 107, 23: 107, 30: 107, 107, 107, 107},
		{6: 386, 390, 9: 389, 15: 391, 385, 420, 25: 388, 387, 384, 29: 383, 34: 419},
		{6: 386, 390, 9: 389, 15: 391, 385, 416, 25: 388, 387, 384, 29: 383, 34: 417},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 415},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 414},
		// 275
		{109, 109, 6: 109, 10: 109, 16: 109, 109, 20: 109, 109, 23: 109, 30: 109, 109, 407, 406},
		{110, 110, 6: 110, 10: 110, 16: 110, 110, 20: 110, 110, 23: 110, 30: 110, 110, 407, 406},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 418},
		{112, 112, 6: 413, 10: 412, 16: 112, 112, 20: 112, 112, 23: 112},
		{113, 113, 6: 413, 10: 412, 16: 113, 113, 20: 113, 113, 23: 113},
		// 280
		{115, 115, 6: 413, 10: 412, 16: 115, 115, 20: 115, 115, 23: 115},
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 421},
		{114, 114, 6: 413, 10: 412, 16: 114, 114, 20: 114, 114, 23: 114},
		{1: 129, 6: 163, 161, 162, 10: 183, 164, 160, 14: 159, 17: 191, 190, 35: 165, 155, 158, 156, 166, 179, 175, 157, 176, 144, 151, 154, 152, 153, 187, 184, 188, 186, 146, 189, 185, 145, 58: 423, 177, 182, 181, 178, 169, 172, 171, 170, 168, 173, 174, 167, 180, 192},
		{1: 424},
		// 285
		{1: 425},
		{426},
		{129, 2: 129, 6: 163, 161, 162, 10: 183, 164, 160, 14: 159, 17: 191, 190, 35: 165, 155, 158, 156, 166, 179, 175, 157, 176, 144, 151, 154, 152, 153, 187, 184, 188, 186, 146, 189, 185, 145, 58: 142, 177, 182, 181, 178, 169, 172, 171, 170, 168, 173, 174, 167, 180, 192, 143, 147, 427, 150, 148, 149},
		{2: 428},
		{2: 124, 124, 124, 124},
		// 290
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 382, 57: 381, 79: 380, 81: 379, 430},
		{1: 431, 20: 393},
		{129, 2: 129, 6: 163, 161, 162, 10: 183, 164, 160, 14: 159, 17: 191, 190, 35: 165, 155, 158, 156, 166, 179, 175, 157, 176, 144, 151, 154, 152, 153, 187, 184, 188, 186, 146, 189, 185, 145, 58: 142, 177, 182, 181, 178, 169, 172, 171, 170, 168, 173, 174, 167, 180, 192, 143, 147, 432, 150, 148, 149},
		{2: 433},
		{2: 125, 125, 125, 125},
		// 295
		{6: 386, 390, 9: 389, 15: 391, 385, 25: 388, 387, 384, 29: 383, 34: 382, 57: 381, 79: 380, 81: 379, 435},
		{20: 393, 436},
		{109: 437},
		{129, 3: 129, 5: 129, 163, 161, 162, 10: 183, 164, 160, 14: 159, 17: 191, 190, 35: 165, 155, 158, 156, 166, 179, 175, 157, 176, 144, 151, 154, 152, 153, 187, 184, 188, 186, 146, 189, 185, 145, 58: 142, 177, 182, 181, 178, 169, 172, 171, 170, 168, 173, 174, 167, 180, 192, 143, 147, 438, 150, 148, 149},
		{3: 439, 5: 440},
		// 300
		{2: 127, 127, 127, 127},
		{129, 3: 129, 6: 163, 161, 162, 10: 183, 164, 160, 14: 159, 17: 191, 190, 35: 165, 155, 158, 156, 166, 179, 175, 157, 176, 144, 151, 154, 152, 153, 187, 184, 188, 186, 146, 189, 185, 145, 58: 142, 177, 182, 181, 178, 169, 172, 171, 170, 168, 173, 174, 167, 180, 192, 143, 147, 441, 150, 148, 149},
		{3: 442},
		{2: 126, 126, 126, 126},
		{2: 137, 137, 137, 137},
		// 305
		{129, 2: 134, 134, 134, 134, 163, 161, 162, 10: 183, 164, 160, 14: 159, 17: 191, 190, 35: 165, 155, 158, 156, 166, 179, 175, 157, 176, 144, 151, 154, 152, 153, 187, 184, 188, 186, 146, 189, 185, 145, 58: 142, 177, 182, 181, 178, 169, 172, 171, 170, 168, 173, 174, 167, 180, 192, 143, 147, 445, 150, 148, 149},
		{2: 136, 136, 136, 136},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 112

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			println("OGREE: Unrecognised command!")
cmd.WarningLogger.Println("Unknown Command")			/*yylex.Error(msg)*/
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			root = yyS[yypt-0].node
		}
	case 2:
		{ /*$$=[]node{$1}*/
			yyVAL.node = &ast{BLOCK, []node{yyS[yypt-1].node}}
		}
	case 3:
		{
			yyVAL.node = &ast{BLOCK, []node{yyS[yypt-2].node, yyS[yypt-0].node}}
		}
	case 4:
		{
			yyVAL.node = &ast{IF, []node{yyS[yypt-0].node}}
		}
	case 7:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 8:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 9:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 10:
		{
			yyVAL.node = nil
		}
	case 11:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 12:
		{
			yyVAL.node = &ifNode{IF, yyS[yypt-4].node, yyS[yypt-1].node, nil}
		}
	case 13:
		{
			yyVAL.node = &ifNode{IF, yyS[yypt-6].node, yyS[yypt-3].node, yyS[yypt-1].node}
		}
	case 14:
		{
			yyVAL.node = &whileNode{WHILE, yyS[yypt-3].node, yyS[yypt-1].node}
		}
	case 15:
		{
			initnd := &assignNode{ASSIGN, yyS[yypt-11].s, dCatchNodePtr}
			yyVAL.node = &forNode{FOR, initnd, yyS[yypt-7].node, yyS[yypt-5].node, yyS[yypt-1].node}
		}
	case 16:
		{
			n1 := &numNode{NUM, yyS[yypt-7].n}
			n2 := &numNode{NUM, yyS[yypt-4].n}
			initnd := &assignNode{ASSIGN, yyS[yypt-10].s, n1}
			var cond *comparatorNode
			var incr *arithNode
			var iter *symbolReferenceNode
			var incrAssign *assignNode

			iter = &symbolReferenceNode{NUM, yyS[yypt-10].s}

			if yyS[yypt-7].n < yyS[yypt-4].n {
				cond = &comparatorNode{COMPARATOR, "<", iter, n2}
				incr = &arithNode{ARITHMETIC, "+", iter, &numNode{NUM, 1}}
				incrAssign = &assignNode{ASSIGN, iter, incr} //Maybe redundant
			} else if yyS[yypt-7].n == yyS[yypt-4].n {

			} else { //$5 > 8
				cond = &comparatorNode{COMPARATOR, ">", iter, n2}
				incr = &arithNode{ARITHMETIC, "-", iter, &numNode{NUM, 1}}
				incrAssign = &assignNode{ASSIGN, iter, incr}
			}
			yyVAL.node = &forNode{FOR, initnd, cond, incrAssign, yyS[yypt-1].node}
		}
	case 20:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 21:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, "==", yyS[yypt-3].node, yyS[yypt-0].node}
		}
	case 22:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, "!=", yyS[yypt-3].node, yyS[yypt-0].node}
		}
	case 23:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 24:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, "<", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 25:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, "<=", yyS[yypt-3].node, yyS[yypt-0].node}
		}
	case 26:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, ">=", yyS[yypt-3].node, yyS[yypt-0].node}
		}
	case 27:
		{
			yyVAL.node = &comparatorNode{COMPARATOR, ">", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 28:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 29:
		{
			yyVAL.node = &arithNode{ARITHMETIC, "+", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 30:
		{
			yyVAL.node = &arithNode{ARITHMETIC, "-", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 31:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 32:
		{
			yyVAL.node = &arithNode{ARITHMETIC, "*", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 33:
		{
			yyVAL.node = &arithNode{ARITHMETIC, "/", yyS[yypt-2].node, yyS[yypt-0].node}
		}
	case 34:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 35:
		{
			yyVAL.node = &boolOpNode{BOOLOP, "!", yyS[yypt-0].node}
		}
	case 36:
		{
			left := &numNode{NUM, 0}
			yyVAL.node = &arithNode{ARITHMETIC, "-", left, yyS[yypt-0].node}
		}
	case 37:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 38:
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 39:
		{
			yyVAL.node = &numNode{NUM, yyS[yypt-0].n}
		}
	case 40:
		{
			yyVAL.node = &symbolReferenceNode{REFERENCE, yyS[yypt-0].s}
		}
	case 41:
		{
			var x bool
			if yyS[yypt-0].s == "false" {
				x = false
			} else {
				x = true
			}
			yyVAL.node = &boolNode{BOOL, x}
		}
	case 42:
		{
			println("@State start")
		}
	case 46:
		{
			yyVAL.node = &commonNode{COMMON, cmd.PostObj, "PostObj", []interface{}{cmd.EntityStrToInt(yyS[yypt-1].s), yyS[yypt-1].s, resMap(&yyS[yypt-0].s)}}
		}
	case 47:
		{
			cmd.Disp(resMap(&yyS[yypt-0].s))
			yyVAL.node = &commonNode{COMMON, cmd.PostObj, "PostObj", []interface{}{cmd.EntityStrToInt(yyS[yypt-2].s), yyS[yypt-2].s, resMap(&yyS[yypt-0].s)}}
		}
	case 48:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetObject, "GetObject", []interface{}{yyS[yypt-0].s}}
		}
	case 49:
		{ /*cmd.Disp(resMap(&$4)); */
			yyVAL.node = &commonNode{COMMON, cmd.SearchObjects, "SearchObjects", []interface{}{yyS[yypt-1].s, resMap(&yyS[yypt-0].s)}}
		}
	case 50:
		{
			yyVAL.node = &commonNode{COMMON, cmd.UpdateObj, "UpdateObj", []interface{}{yyS[yypt-1].s, resMap(&yyS[yypt-0].s)}}
		}
	case 51:
		{
			println("@State NT_DEL")
			yyVAL.node = &commonNode{COMMON, cmd.DeleteObj, "DeleteObj", []interface{}{yyS[yypt-0].s}}
		}
	case 60:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 61:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 62:
		{
			yyVAL.s = ""
		}
	case 63:
		{
			yyVAL.s = yyS[yypt-0].s
			dCatchPtr = yyS[yypt-0].s
			dCatchNodePtr = &strNode{STR, yyS[yypt-0].s}
		}
	case 64:
		{
			x := strconv.Itoa(yyS[yypt-0].n)
			yyVAL.s = x
			dCatchPtr = yyS[yypt-0].n
			dCatchNodePtr = &numNode{NUM, yyS[yypt-0].n}
		}
	case 65:
		{
			yyVAL.s = yyS[yypt-3].s + yyS[yypt-2].s + yyS[yypt-1].s + yyS[yypt-0].s
			dCatchPtr = yyS[yypt-3].s + yyS[yypt-2].s + yyS[yypt-1].s + yyS[yypt-0].s
			dCatchNodePtr = &strNode{STR, yyS[yypt-3].s + yyS[yypt-2].s + yyS[yypt-1].s + yyS[yypt-0].s}
		}
	case 66:
		{
			var x bool
			if yyS[yypt-0].s == "false" {
				x = false
			} else {
				x = true
			}
			dCatchPtr = x
			dCatchNodePtr = &boolNode{BOOL, x}
		}
	case 67:
		{
			yyVAL.s = string(yyS[yypt-3].s + "=" + yyS[yypt-1].s + "=" + yyS[yypt-0].s)
			println("So we got: ", yyVAL.s)
		}
	case 68:
		{
			yyVAL.s = yyS[yypt-2].s + "=" + yyS[yypt-0].s
		}
	case 70:
		{
			yyVAL.s = "/" + yyS[yypt-0].s
		}
	case 71:
		{
			yyVAL.s = yyS[yypt-2].s + "/" + yyS[yypt-0].s
		}
	case 72:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 73:
		{
			yyVAL.s = "../" + yyS[yypt-0].s
		}
	case 74:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 75:
		{
			yyVAL.s = ".."
		}
	case 76:
		{
			yyVAL.s = "-"
		}
	case 77:
		{
			yyVAL.s = ""
		}
	case 78:
		{
			yyVAL.s = ""
		}
	case 79:
		{ /*cmd.CD($2);*/
			yyVAL.node = &commonNode{COMMON, cmd.CD, "CD", []interface{}{yyS[yypt-0].s}}
		}
	case 80:
		{ /*cmd.LS($2)*/
			yyVAL.node = &commonNode{COMMON, cmd.LS, "LS", []interface{}{yyS[yypt-0].s}}
		}
	case 81:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 0}}
		}
	case 82:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 1}}
		}
	case 83:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 2}}
		}
	case 84:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 3}}
		}
	case 85:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 4}}
		}
	case 86:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 5}}
		}
	case 87:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 6}}
		}
	case 88:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOBJECT, "LSOBJ", []interface{}{yyS[yypt-0].s, 7}}
		}
	case 89:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Tree, "Tree", []interface{}{"", yyS[yypt-0].n}}
		}
	case 90:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Tree, "Tree", []interface{}{yyS[yypt-0].s, 0}}
		}
	case 91:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Tree, "Tree", []interface{}{yyS[yypt-1].s, yyS[yypt-0].n}}
		}
	case 92:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 93:
		{
			yyVAL.node = &commonNode{COMMON, nil, "CLR", nil}
		}
	case 94:
		{
			yyVAL.node = &commonNode{COMMON, nil, "Grep", nil}
		}
	case 95:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LSOG, "LSOG", nil}
		}
	case 96:
		{
			yyVAL.node = &commonNode{COMMON, cmd.PWD, "PWD", nil}
		}
	case 97:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Exit, "Exit", nil}
		}
	case 98:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{""}}
		}
	case 99:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"ls"}}
		}
	case 100:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"cd"}}
		}
	case 101:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"create"}}
		}
	case 102:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"gt"}}
		}
	case 103:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"update"}}
		}
	case 104:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"delete"}}
		}
	case 105:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{yyS[yypt-0].s}}
		}
	case 106:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"tree"}}
		}
	case 107:
		{
			yyVAL.node = &commonNode{COMMON, cmd.Help, "Help", []interface{}{"lsog"}}
		}
	case 108:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 109:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 110:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 111:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 112:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 113:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 114:
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 115:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-2].s)), cmd.TENANT, map[string]interface{}{"attributes": map[string]interface{}{"color": yyS[yypt-0].s}}, rlPtr}}
		}
	case 116:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-2].s)), cmd.TENANT, map[string]interface{}{"attributes": map[string]interface{}{"color": yyS[yypt-0].s}}, rlPtr}}
		}
	case 117:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-2].s)), cmd.SITE, map[string]interface{}{"attributes": map[string]interface{}{"orientation": yyS[yypt-0].s}}, rlPtr}}
		}
	case 118:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-2].s)), cmd.SITE, map[string]interface{}{"attributes": map[string]interface{}{"orientation": yyS[yypt-0].s}}, rlPtr}}
		}
	case 119:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.BLDG, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 120:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.BLDG, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 121:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.ROOM, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 122:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.ROOM, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 123:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.RACK, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 124:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.RACK, map[string]interface{}{"attributes": map[string]interface{}{"posXY": yyS[yypt-2].s, "size": yyS[yypt-0].s}}, rlPtr}}
		}
	case 125:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.DEVICE, map[string]interface{}{"attributes": map[string]interface{}{"slot": yyS[yypt-2].s, "sizeUnit": yyS[yypt-0].s}}, rlPtr}}
		}
	case 126:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetOCLIAtrributes, "GetOCAttr", []interface{}{cmd.StrToStack(replaceOCLICurrPath(yyS[yypt-4].s)), cmd.DEVICE, map[string]interface{}{"attributes": map[string]interface{}{"slot": yyS[yypt-2].s, "sizeUnit": yyS[yypt-0].s}}, rlPtr}}
		}
	case 127:
		{
			yyVAL.node = &commonNode{COMMON, cmd.DeleteObj, "DeleteObj", []interface{}{replaceOCLICurrPath(yyS[yypt-0].s)}}
		}
	case 128:
		{
			val := yyS[yypt-2].s + "=" + yyS[yypt-0].s
			yyVAL.node = &commonNode{COMMON, cmd.UpdateObj, "UpdateObj", []interface{}{replaceOCLICurrPath(yyS[yypt-4].s), resMap(&val)}}
			println("Attribute Acquired")
		}
	case 129:
		{
			yyVAL.node = &commonNode{COMMON, cmd.GetObject, "GetObject", []interface{}{replaceOCLICurrPath(yyS[yypt-0].s)}}
		}
	case 130:
		{
			x := make([]string, 0)
			x = append(x, cmd.State.CurrPath+"/"+yyS[yypt-2].s)
			x = append(x, yyS[yypt-0].sarr...)
			yyVAL.sarr = x
		}
	case 131:
		{
			yyVAL.sarr = []string{cmd.State.CurrPath + "/" + yyS[yypt-0].s}
		}
	case 132:
		{
			yyVAL.node = &commonNode{COMMON, cmd.SetClipBoard, "setCB", []interface{}{&yyS[yypt-1].sarr}}
			println("Selection made!")
		}
	case 133:
		{
			yyVAL.node = &assignNode{ASSIGN, yyS[yypt-2].s, dCatchNodePtr}
		}
	case 134:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LoadFile, "Load", []interface{}{yyS[yypt-0].s}}
		}
	case 135:
		{
			yyVAL.node = &commonNode{COMMON, cmd.LoadFile, "Load", []interface{}{yyS[yypt-0].s}}
		}
	case 136:
		{
			yyVAL.node = &symbolReferenceNode{REFERENCE, yyS[yypt-0].s}
		}
	case 137:
		{
			yyVAL.node = &commonNode{COMMON, cmd.ShowClipBoard, "select", nil}
		}
	case 138:
		{
			x := yyS[yypt-2].s + "=" + yyS[yypt-0].s
			yyVAL.node = &commonNode{COMMON, cmd.UpdateSelection, "UpdateSelect", []interface{}{resMap(&x)}}
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
