// Code generated by goyacc - DO NOT EDIT.

package main

import __yyfmt__ "fmt"

import (
	"cli/cmd"
	"cli/utils"
	"strings"
)

func resMap(x *string) map[string]string {
	resarr := strings.Split(*x, "=")
	res := make(map[string]string)

	for i := 0; i+1 < len(resarr); {
		if i+1 < len(resarr) {
			res[resarr[i]] = resarr[i+1]
			i += 2
		}
	}
	return res
}

type yySymType struct {
	yys int
	//n int
	s string
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault        = 57371
	yyEofCode        = 57344
	TOKEN_ATTR       = 57355
	TOKEN_BASHTYPE   = 57360
	TOKEN_BLDG       = 57349
	TOKEN_CD         = 57366
	TOKEN_CLR        = 57368
	TOKEN_CMDFLAG    = 57362
	TOKEN_CREATE     = 57356
	TOKEN_DELETE     = 57359
	TOKEN_DEVICE     = 57352
	TOKEN_DOC        = 57365
	TOKEN_EQUAL      = 57361
	TOKEN_EXIT       = 57364
	TOKEN_GET        = 57357
	TOKEN_GREP       = 57369
	TOKEN_LS         = 57370
	TOKEN_PWD        = 57367
	TOKEN_RACK       = 57351
	TOKEN_ROOM       = 57350
	TOKEN_SITE       = 57348
	TOKEN_SLASH      = 57363
	TOKEN_SUBDEVICE  = 57353
	TOKEN_SUBDEVICE1 = 57354
	TOKEN_TENANT     = 57347
	TOKEN_UPDATE     = 57358
	TOKEN_WORD       = 57346
	yyErrCode        = 57345

	yyMaxDepth = 200
	yyTabOfs   = -39
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57344: 0,  // $end (29x)
		57346: 1,  // TOKEN_WORD (22x)
		57355: 2,  // TOKEN_ATTR (19x)
		57374: 3,  // F (9x)
		57381: 4,  // P (5x)
		57373: 5,  // E (4x)
		57349: 6,  // TOKEN_BLDG (4x)
		57352: 7,  // TOKEN_DEVICE (4x)
		57351: 8,  // TOKEN_RACK (4x)
		57350: 9,  // TOKEN_ROOM (4x)
		57348: 10, // TOKEN_SITE (4x)
		57353: 11, // TOKEN_SUBDEVICE (4x)
		57354: 12, // TOKEN_SUBDEVICE1 (4x)
		57347: 13, // TOKEN_TENANT (4x)
		57362: 14, // TOKEN_CMDFLAG (2x)
		57372: 15, // BASH (1x)
		57375: 16, // K (1x)
		57376: 17, // M (1x)
		57377: 18, // NT_CREATE (1x)
		57378: 19, // NT_DEL (1x)
		57379: 20, // NT_GET (1x)
		57380: 21, // NT_UPDATE (1x)
		57382: 22, // Q (1x)
		57383: 23, // start (1x)
		57366: 24, // TOKEN_CD (1x)
		57368: 25, // TOKEN_CLR (1x)
		57356: 26, // TOKEN_CREATE (1x)
		57359: 27, // TOKEN_DELETE (1x)
		57365: 28, // TOKEN_DOC (1x)
		57361: 29, // TOKEN_EQUAL (1x)
		57364: 30, // TOKEN_EXIT (1x)
		57357: 31, // TOKEN_GET (1x)
		57369: 32, // TOKEN_GREP (1x)
		57370: 33, // TOKEN_LS (1x)
		57367: 34, // TOKEN_PWD (1x)
		57363: 35, // TOKEN_SLASH (1x)
		57358: 36, // TOKEN_UPDATE (1x)
		57371: 37, // $default (0x)
		57345: 38, // error (0x)
		57360: 39, // TOKEN_BASHTYPE (0x)
	}

	yySymNames = []string{
		"$end",
		"TOKEN_WORD",
		"TOKEN_ATTR",
		"F",
		"P",
		"E",
		"TOKEN_BLDG",
		"TOKEN_DEVICE",
		"TOKEN_RACK",
		"TOKEN_ROOM",
		"TOKEN_SITE",
		"TOKEN_SUBDEVICE",
		"TOKEN_SUBDEVICE1",
		"TOKEN_TENANT",
		"TOKEN_CMDFLAG",
		"BASH",
		"K",
		"M",
		"NT_CREATE",
		"NT_DEL",
		"NT_GET",
		"NT_UPDATE",
		"Q",
		"start",
		"TOKEN_CD",
		"TOKEN_CLR",
		"TOKEN_CREATE",
		"TOKEN_DELETE",
		"TOKEN_DOC",
		"TOKEN_EQUAL",
		"TOKEN_EXIT",
		"TOKEN_GET",
		"TOKEN_GREP",
		"TOKEN_LS",
		"TOKEN_PWD",
		"TOKEN_SLASH",
		"TOKEN_UPDATE",
		"$default",
		"error",
		"TOKEN_BASHTYPE",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {23, 1},
		2:  {23, 1},
		3:  {16, 1},
		4:  {16, 1},
		5:  {16, 1},
		6:  {16, 1},
		7:  {18, 3},
		8:  {18, 4},
		9:  {20, 3},
		10: {20, 4},
		11: {21, 3},
		12: {21, 4},
		13: {19, 3},
		14: {19, 4},
		15: {5, 1},
		16: {5, 1},
		17: {5, 1},
		18: {5, 1},
		19: {5, 1},
		20: {5, 1},
		21: {5, 1},
		22: {5, 1},
		23: {3, 4},
		24: {3, 4},
		25: {17, 0},
		26: {4, 3},
		27: {4, 1},
		28: {22, 3},
		29: {22, 3},
		30: {22, 2},
		31: {22, 1},
		32: {15, 1},
		33: {15, 1},
		34: {15, 1},
		35: {15, 1},
		36: {15, 1},
		37: {15, 1},
		38: {15, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [57][]uint8{
		// 0
		{15: 53, 41, 18: 43, 46, 44, 45, 42, 40, 51, 54, 47, 50, 58, 30: 57, 48, 55, 52, 56, 36: 49},
		{39},
		{38},
		{37},
		{36},
		// 5
		{35},
		{34},
		{33},
		{5: 92, 67, 70, 69, 68, 66, 71, 72, 65},
		{5: 88, 67, 70, 69, 68, 66, 71, 72, 65},
		// 10
		{5: 84, 67, 70, 69, 68, 66, 71, 72, 65},
		{5: 64, 67, 70, 69, 68, 66, 71, 72, 65},
		{7, 62},
		{4, 60},
		{8, 59},
		// 15
		{6, 6},
		{5, 5},
		{3, 3},
		{2, 2},
		{1, 1},
		// 20
		{9},
		{14: 61},
		{10},
		{14: 63},
		{11},
		// 25
		{1: 76, 75, 73, 74},
		{1: 24, 24},
		{1: 23, 23},
		{1: 22, 22},
		{1: 21, 21},
		// 30
		{1: 20, 20},
		{1: 19, 19},
		{1: 18, 18},
		{1: 17, 17},
		{26},
		// 35
		{2: 75, 83},
		{29: 79},
		{2: 12, 35: 77},
		{1: 76, 4: 78},
		{2: 13},
		// 40
		{1: 80},
		{14, 2: 75, 81, 17: 82},
		{16},
		{15},
		{25},
		// 45
		{1: 76, 75, 85, 86},
		{28},
		{2: 75, 87},
		{27},
		{1: 76, 75, 89, 90},
		// 50
		{30},
		{2: 75, 91},
		{29},
		{1: 76, 75, 93, 94},
		{32},
		// 55
		{2: 75, 95},
		{31},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 38

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			println("@State start")
		}
	case 7:
		{
			println("@State NT_CR")
		}
	case 8:
		{
			yyVAL.s = yyS[yypt-0].s /*println("Finally: "+$$);*/
			cmd.Disp(resMap(&yyS[yypt-0].s))
		}
	case 9:
		{
			println("@State NT_GET")
		}
	case 10:
		{
			yyVAL.s = yyS[yypt-0].s
			cmd.Disp(resMap(&yyS[yypt-0].s))
		}
	case 11:
		{
			println("@State NT_UPD")
		}
	case 12:
		{
			yyVAL.s = yyS[yypt-0].s
			cmd.Disp(resMap(&yyS[yypt-0].s))
		}
	case 13:
		{
			println("@State NT_DEL")
		}
	case 14:
		{
			yyVAL.s = yyS[yypt-0].s
			cmd.Disp(resMap(&yyS[yypt-0].s))
		}
	case 23:
		{
			yyVAL.s = string(yyS[yypt-3].s + "=" + yyS[yypt-1].s + "=" + yyS[yypt-0].s)
			println("So we got: ", yyVAL.s)
		}
	case 24:
		{
			yyVAL.s = yyS[yypt-3].s + "=" + yyS[yypt-1].s
			println("Taking the M")
			println("SUP DUDE: ", yyS[yypt-1].s)
		}
	case 31:
		{
			cmd.Execute()
		}
	case 36:
		{
			cmd.PWD(&(utils.State.CurrPath))
		}
	case 37:
		{
			utils.Exit()
		}
	case 38:
		{
			cmd.Help()
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
