FROM golang:1.18.2-alpine3.16 AS build

# Set the Current Working Directory inside the container
WORKDIR /build

# We want to populate the module cache based on the go.{mod,sum} files.
COPY ARANGO_API/go.mod .
COPY ARANGO_API/go.sum .
	
RUN go mod download

COPY ARANGO_API/. .


# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -a -o arango-api  -ldflags "-X main.version=${VERSION} -X 'main.build=$(date)'" .

# Start fresh from a smaller image
FROM alpine:3.16

WORKDIR /bin

COPY --from=build /build/arango-api .
COPY --from=build /build/swagger.yaml .


# Run the binary program produced by `go install`
CMD ["./arango-api"]

