basePath: /api/v1
consumes:
    - application/json
definitions:
    Connection:
        properties:
            _from:
                description: |-
                    from Device
                    in: _from
                example: devices/*
                type: string
                x-go-name: From
            _key:
                description: |-
                    Primary key of device
                    in: _key
                readOnly: true
                type: string
                x-go-name: Key
            _to:
                description: |-
                    To device
                    in: _to
                example: devices/*
                type: string
                x-go-name: To
            created:
                description: |-
                    Date of connection's creation
                    in: created
                example: "2016-04-22"
                type: string
                x-go-name: Created
            expired:
                description: |-
                    Date of connection's expiration
                    in: expired
                example: "3000-01-01"
                type: string
                x-go-name: Expired
            type:
                description: |-
                    Type of connection
                    in: type
                example: parent of (between partens)
                type: string
                x-go-name: Type
        type: object
        x-go-package: arango-api/models
    DatabaseInfo:
        properties:
            database:
                description: |-
                    Database name
                    in: database
                example: _system
                type: string
                x-go-name: Database
            host:
                description: |-
                    Host url of database
                    in: host
                example: http://localhost:8529
                type: string
                x-go-name: Host
            password:
                description: |-
                    Password of the user
                    in: password
                example: password
                type: string
                x-go-name: Password
            user:
                description: |-
                    User of database
                    in: user
                example: root
                type: string
                x-go-name: User
        type: object
        x-go-package: arango-api/models
    Devices:
        properties:
            _key:
                description: |-
                    Primary key of device
                    in: _key
                readOnly: true
                type: string
                x-go-name: Key
            _name:
                description: |-
                    name of Devices
                    in: _name
                example: storage_bay
                type: string
                x-go-name: Name
            category:
                description: |-
                    category of Devices
                    in: category
                example: port
                type: string
                x-go-name: Category
            created:
                description: |-
                    Date of device's creation
                    in: created
                example: "2016-04-22"
                type: string
                x-go-name: Created
            expired:
                description: |-
                    Date of device's expiration
                    in: expired
                example: "3000-01-01"
                type: string
                x-go-name: Expired
            group_name:
                description: |-
                    group_name of Devices
                    in: group_name
                example: GS00OPSAN06
                type: string
                x-go-name: GroupName
            hba_device_name:
                description: |-
                    hba_device_name of Devices
                    in: hba_device_name
                example: nsa.*
                type: string
                x-go-name: HbaDeviceName
            sp_name:
                description: |-
                    sp_name of Devices
                    in: sp_name
                example: sp_b
                type: string
                x-go-name: SpName
            sp_port_id:
                description: |-
                    sp_port_id of Devices
                    in: sp_port_id
                example: "0"
                type: string
                x-go-name: SpPortId
            storage_group_name:
                description: |-
                    storage_group_name of Devices
                    in: storage_group_name
                example: storage
                type: string
                x-go-name: StorageGroupName
        type: object
        x-go-package: arango-api/models
    ErrorResponse:
        properties:
            message:
                description: |-
                    Error Response Message
                    in: message
                type: string
                x-go-name: Message
        type: object
        x-go-package: arango-api/models
    LoginInput:
        properties:
            password:
                description: |-
                    username
                    in: password
                type: string
                x-go-name: Password
            username:
                description: |-
                    username
                    in: username
                type: string
                x-go-name: Username
        type: object
        x-go-package: arango-api/models
    SuccessConResponse:
        properties:
            Connections:
                description: |-
                    Success
                    in : array
                items:
                    $ref: '#/definitions/Connection'
                type: array
        type: object
        x-go-package: arango-api/models
    SuccessLogin:
        properties:
            token:
                type: string
                x-go-name: Token
        type: object
        x-go-package: arango-api/models
    SuccessResponse:
        properties:
            Devices:
                description: |-
                    Success
                    in : array
                items:
                    $ref: '#/definitions/Devices'
                type: array
        type: object
        x-go-package: arango-api/models
info:
    title: 'Arrango API:'
    version: 1.0.0
paths:
    /Connections:
        get:
            description: Get Connection list
            operationId: Connection
            parameters:
                - description: Key of connection
                  in: query
                  name: _key
                  type: string
                - description: From witch device
                  in: query
                  name: _from
                  type: string
                - description: To witch device
                  in: query
                  name: _to
                  type: string
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/SuccessConResponse'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            security:
                - Bearer: []
            tags:
                - Connections
        post:
            description: Create new Connection
            operationId: CreateConnection
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/Connection'
                  x-go-name: Body
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/SuccessConResponse'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            security:
                - Bearer: []
            tags:
                - Connections
    /Connections/{connection}:
        delete:
            description: Delete Connection by key
            operationId: DeleteConnection
            parameters:
                - description: connection looking for
                  in: path
                  name: connection
                  required: true
                  type: string
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/SuccessResponse'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            security:
                - Bearer: []
            tags:
                - Connections
    /Database:
        get:
            description: Get database name
            operationId: Database
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            security:
                - Bearer: []
            tags:
                - Database
        post:
            description: Connect to new bdd
            operationId: ConnectBDD
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/DatabaseInfo'
                  x-go-name: Body
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            security:
                - Bearer: []
            tags:
                - Database
    /Devices:
        get:
            description: Get Devices list
            operationId: Devices
            parameters:
                - description: Key of device
                  in: query
                  name: _key
                  type: string
                - description: Name of device
                  in: query
                  name: _name
                  type: string
                - description: Group_name of device
                  in: query
                  name: group_name
                  type: string
                - description: Serial number of device
                  in: query
                  name: serial
                  type: string
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/SuccessResponse'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            security:
                - Bearer: []
            tags:
                - Devices
        post:
            description: Create new Devices
            operationId: CreateDevices
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/Devices'
                  x-go-name: Body
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/SuccessResponse'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            security:
                - Bearer: []
            tags:
                - Devices
    /Devices/{device}:
        delete:
            description: Delete Devices by key
            operationId: DeleteDevices
            parameters:
                - description: device looking for
                  in: path
                  name: device
                  required: true
                  type: string
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/SuccessResponse'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            security:
                - Bearer: []
            tags:
                - Devices
    /Login:
        post:
            description: Login to api
            operationId: LoginToApi
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/LoginInput'
                  x-go-name: Body
            responses:
                "200":
                    description: successful
                    schema:
                        items:
                            $ref: '#/definitions/SuccessLogin'
                "500":
                    description: Error
                    schema:
                        items:
                            $ref: '#/definitions/ErrorResponse'
            tags:
                - Login
produces:
    - application/json
schemes:
    - http
    - https
securityDefinitions:
    Bearer:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
