{{- if .Values.ingress.enabled -}}
{{- $fullnameOverride := .Values.fullnameOverride -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullnameOverride  }}
spec:
  {{- range .Values.ingress.entryPoints }}
  entryPoints:
    - {{ . | quote }}
  {{- end }}
  {{- range .Values.ingress.hosts }}
  routes:
    - kind: Rule
      match: Host(`{{- .host }}`)
      services:
        - name: {{ $fullnameOverride }}
          port: {{ $svcPort }}
  {{- end }}
{{- end }}
