apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: netbox
spec:
  entryPoints:
    - "web"
  routes:
  - kind: Rule
    match: Host(`{{ .Values.host }}`)
    services:
      - name: netbox
        port: 80

        