package repository

import (
	"context"
	u "p3/utils"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

const imagesCollection = "images"

func CreateImage(ctx context.Context, image u.Image) (primitive.ObjectID, *u.Error) {
	return CreateObject(ctx, imagesCollection, image)
}

func GetImage(ctx context.Context, id string) (*u.Image, *u.Error) {
	return GetByAutogeneratedID[u.Image](ctx, imagesCollection, id)
}

func DeleteImage(ctx context.Context, id primitive.ObjectID) *u.Error {
	return DeleteObject(ctx, imagesCollection, bson.M{"_id": id})
}
