package repository

import (
	"context"
	u "p3/utils"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

const imagesCollection = "images"

func CreateImage(ctx context.Context, image []byte) (primitive.ObjectID, *u.Error) {
	return CreateObject(ctx, imagesCollection, map[string]any{
		"data": image,
	})
}

func GetImage(ctx context.Context, id string) ([]byte, error) {
	image, err := GetByAutogeneratedID(ctx, imagesCollection, id)
	if err != nil {
		return nil, err
	}

	return image["data"].(primitive.Binary).Data, nil
}
