// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LayersFactory is an autogenerated mock type for the LayersFactory type
type LayersFactory struct {
	mock.Mock
}

// FromObjects provides a mock function with given fields: objects
func (_m *LayersFactory) FromObjects(objects []interface{}) []interface{} {
	ret := _m.Called(objects)

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func([]interface{}) []interface{}); ok {
		r0 = rf(objects)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}

type mockConstructorTestingTNewLayersFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewLayersFactory creates a new instance of LayersFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLayersFactory(t mockConstructorTestingTNewLayersFactory) *LayersFactory {
	mock := &LayersFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
