version: '3.5'

services:

  webapp:
    image: opendcim/opendcim:23.03
    build: .
    environment:
      - OPENDCIM_DB_HOST=db
      - OPENDCIM_DB_USER=${MYSQL_USER}
      - OPENDCIM_DB_PASS=${MYSQL_PASSWORD}
      - OPENDCIM_DB_NAME=${MYSQL_DATABASE}
      - OPENDCIM_AUTH=LDAP
    volumes:
      - dcim_data:/data
    networks:
      - database_net
      - outside
    ports:
      - ${DCIM_HTTP_PORT}:80
      #- ${DCIM_HTTPS_PORT}:443

  db:
    image: mariadb:10.2.14
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    restart: always
    env_file: .env
    volumes:
      - dcim_db:/var/lib/mysql
    networks:
      - database_net

  adminer:
    image: adminer:4.6.2
    restart: always
    networks:
      - database_net
      - outside
    ports:
      - ${ADMINER_PORT}:8080

networks:
  database_net:
    driver: bridge
    internal: true
  outside:
    driver: bridge

volumes:
  dcim_data:
    driver: local
  dcim_db:
    driver: local

