// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// node is an autogenerated mock type for the node type
type node struct {
	mock.Mock
}

// execute provides a mock function with given fields:
func (_m *node) execute() (interface{}, error) {
	ret := _m.Called()

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func() (interface{}, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewNode interface {
	mock.TestingT
	Cleanup(func())
}

// newNode creates a new instance of node. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newNode(t mockConstructorTestingTnewNode) *node {
	mock := &node{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
