// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// parseCommandFunc is an autogenerated mock type for the parseCommandFunc type
type parseCommandFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *parseCommandFunc) Execute() node {
	ret := _m.Called()

	var r0 node
	if rf, ok := ret.Get(0).(func() node); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(node)
		}
	}

	return r0
}

type mockConstructorTestingTnewParseCommandFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newParseCommandFunc creates a new instance of parseCommandFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newParseCommandFunc(t mockConstructorTestingTnewParseCommandFunc) *parseCommandFunc {
	mock := &parseCommandFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
