apiVersion: v1
kind: ServiceAccount
metadata:
  name: ogree-admin
  namespace: ogree-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ogree-admin
rules:
- apiGroups:
  - ""
  - "apps"
  - "traefik.io"
  - "batch"
  resources:
  - deployments
  - deployments/scale
  - deployments.apps
  - namespaces
  - services
  - ingressroutes
  - secrets
  - pods
  - configmaps
  - persistentvolumeclaims
  - serviceaccounts
  - statefulsets
  - statefulsets.apps
  - cronjobs
  - pods/log
  - pods/exec
  verbs:
  - get
  - list
  - update
  - create
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ogree-admin
subjects:
- kind: ServiceAccount
  name: ogree-admin
  namespace: ogree-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ogree-admin
