replicaCount: 1
fullnameOverride: ogree-bff
imagePullSecrets:
    - name: regcred
image:
    repository: registry.ogree.ditrit.io/ogree-bff
    pullPolicy: Always
    tag: 1.1.0.rc
env:
    - name: ENV
      value: production
    - name: BFF_PORT
      value: "8085"
    - name: BFF_SECRET
      value: myAwesomeApiSecret
service:
    type: NodePort
    port: 8085
ingress:
    enabled: true
    entryPoints:
        - web
    hosts:
        - host: api.test.localhost
configmap:
    - name: api-list
      data:
        - mountPath: /bin/api.json
          name: api-list
          value: |
            [{"name":"server","url":"http://arango-api:8080"},{"name":"objects","url":"http://mongo-api:3001"}]
securityContext: null
