name: Extract project version and name
description: Extract project version and name depending on branch

inputs:
  ENVIRONMENT:
    description: "Environment name"
    default: "Release Candidate"
    required: false

runs:
  using: composite
  steps:
    
    - name: Get last tag
      uses: ./.github/actions/versioning/get-last-tag

    - name: 🆙 Determine bump level from commit messages if release
      shell: bash
      run: |
        COMMIT_LIST=$(git log ${{ env.VERSION }}..HEAD --oneline)
        BUMP_LEVEL="bug"

        while IFS= read -r commit_msg; do
            echo "... $commit_msg ..."
            if [[ $commit_msg == *'break'* ]]; then
                BUMP_LEVEL="major"
                break
            fi
            if [[ $commit_msg == *'feat'* ]]; then
                BUMP_LEVEL="feature"
            fi
        done <<< "$COMMIT_LIST"

        echo "BUMP_LEVEL=$BUMP_LEVEL" >> $GITHUB_ENV


    - name: 🆙 Bump version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.3
      with:
        current-version: "${{ env.VERSION }}"
        version-fragment: "${{ env.BUMP_LEVEL }}"

    - name: 🆕 Update env if bumped
      shell: bash
      run: |
          echo "VERSION=${{ steps.bump_version.outputs.next-version }}" >> $GITHUB_ENV
