
- name: api_port
  value: "3001"
- name: db_host
  value: mongo-db
- name: db_port
  value: "27017"
- name: db_user
  value: ogree-core
- name: db_pass
  value: test
- name: db
  value: ogree-core
- name: token_password
  value: myAwesomeApiSecret