// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ClockPort is an autogenerated mock type for the ClockPort type
type ClockPort struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *ClockPort) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

type mockConstructorTestingTNewClockPort interface {
	mock.TestingT
	Cleanup(func())
}

// NewClockPort creates a new instance of ClockPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClockPort(t mockConstructorTestingTNewClockPort) *ClockPort {
	mock := &ClockPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
