// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteController is an autogenerated mock type for the DeleteController type
type DeleteController struct {
	mock.Mock
}

// DeleteObj provides a mock function with given fields: path
func (_m *DeleteController) DeleteObj(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteController interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteController creates a new instance of DeleteController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteController(t mockConstructorTestingTNewDeleteController) *DeleteController {
	mock := &DeleteController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
