// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	controllers "cli/controllers"

	mock "github.com/stretchr/testify/mock"
)

// FillFunc is an autogenerated mock type for the FillFunc type
type FillFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: n, path, depth
func (_m *FillFunc) Execute(n *controllers.HierarchyNode, path string, depth int) error {
	ret := _m.Called(n, path, depth)

	var r0 error
	if rf, ok := ret.Get(0).(func(*controllers.HierarchyNode, string, int) error); ok {
		r0 = rf(n, path, depth)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewFillFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewFillFunc creates a new instance of FillFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFillFunc(t mockConstructorTestingTNewFillFunc) *FillFunc {
	mock := &FillFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
