// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UpdateController is an autogenerated mock type for the UpdateController type
type UpdateController struct {
	mock.Mock
}

// UpdateObj provides a mock function with given fields: path, data
func (_m *UpdateController) UpdateObj(path string, data map[string]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(path, data)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) (map[string]interface{}, error)); ok {
		return rf(path, data)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(path, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, map[string]interface{}) error); ok {
		r1 = rf(path, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUpdateController interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateController creates a new instance of UpdateController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateController(t mockConstructorTestingTNewUpdateController) *UpdateController {
	mock := &UpdateController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
