name: CLI Publish

on:
  push:
    branches: [ "main" ]
    paths:
    - CLI/**

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CLI
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make main && make mac && make win

    - name: Send to Nextcloud
      shell: bash
      env:
        NEXT_CREDENTIALS: ${{ secrets.NEXT_CREDENTIALS }}
        NEXT_ADDR: https://nextcloud.ditrit.io/remote.php/dav/files/github.actions/Ogree/1_Core/2_CLI/bin
      run: | 
        curl -u $NEXT_CREDENTIALS -T cli $NEXT_ADDR/OGrEE_CLI_Linux_$(date +%Y_%m_%d)
        curl -u $NEXT_CREDENTIALS -T cli.mac $NEXT_ADDR/OGrEE_CLI_OSX_$(date +%Y_%m_%d)
        curl -u $NEXT_CREDENTIALS -T cli.exe $NEXT_ADDR/OGrEE_CLI_Win_$(date +%Y_%m_%d).exe