name: Branch Up to date

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  branch-up-to-date:
    runs-on: ubuntu-latest
    name: 🆕 Check Branch Up to Date
    steps:
      - uses: actions/checkout@v3.2.0

      - name: ✅ Check up to date
        id: checkuptodate
        if: github.base_ref == 'main'
        run: |
          git fetch
          echo "base ref is main checking if branch is up to date..."
          count=$(git rev-list --count origin/${{ github.head_ref }}..origin/${{ github.base_ref }})
          if [ $count == 0 ]; then
            echo "[SUCCESS] - Your branch is up to date"  
          else
            echo "[FAIL] - your branch is $count commits late. Please rebase."  
            exit 1
          fi
