name: Documentation

on:
  push:
    branches:
      - fix396-wiki-conflicts
    # paths:
    #   - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki/
          destination: wiki
          token: ${{ secrets.WIKI_ACTION_TOKEN }} 
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WIKI_ACTION_TOKEN }}  # allows us to push back to repo
          ref: develop
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: wiki/
          token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
          # gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          # gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
          branch: fix396-wiki-conflicts # since default branch is develop in this example