name: 📚 Bi-directional Wiki Sync

on:
  push:
    branches:
      - main
    paths:
      - "wiki/**"
  gollum:

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki/
          destination: wiki
          token: ${{ secrets.WIKI_ACTION_TOKEN }} 
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WIKI_ACTION_TOKEN }}  # allows us to push back to repo
          ref: fix396-wiki-conflicts
      - name: Sync Wiki to Docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: wiki/
          token: ${{ secrets.WIKI_ACTION_TOKEN }} 
          branch: main